// Code generated by cmd/generate from openapi.yaml. DO NOT EDIT.

package voiceblender

import (
	"encoding/json"
	"fmt"
	"time"
)

// Event is the base envelope for all webhook/WebSocket events.
type Event struct {
	Type       WebhookEventType `json:"type"`
	Timestamp  time.Time        `json:"timestamp"`
	InstanceID string           `json:"instance_id,omitempty"`
}

// LegRingingEvent is fired when: sIP call ringing (inbound or outbound)
type LegRingingEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Leg type (e.g. sip_inbound, sip_outbound).
	LegType string `json:"leg_type,omitempty"`
	// Dialed SIP URI (outbound only).
	URI string `json:"uri,omitempty"`
	// Caller URI (inbound) or From header value (outbound, if set).
	From string `json:"from,omitempty"`
	// Callee URI (inbound only).
	To string `json:"to,omitempty"`
	// X-* custom SIP headers, if present.
	SIPHeaders    map[string]string `json:"sip_headers,omitempty"`
	OfferedCodecs []OfferedCodec    `json:"offered_codecs,omitempty"`
	TrunkID       string            `json:"trunk_id,omitempty"`
	SourceAddress string            `json:"source_address,omitempty"`
	Authenticated bool              `json:"authenticated,omitempty"`
	AuthUsername  string            `json:"auth_username,omitempty"`
}

// LegEarlyMediaEvent is fired when: outbound leg received 183 Session Progress with SDP; media pipeline active
type LegEarlyMediaEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Leg type (e.g. sip_outbound).
	LegType string `json:"leg_type,omitempty"`
}

// LegConnectedEvent is fired when: leg answered/connected
type LegConnectedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Leg type (e.g. sip_inbound, sip_outbound, webrtc).
	LegType string `json:"leg_type,omitempty"`
}

// LegDisconnectedEvent is fired when: leg hung up (CDR-style nested structure)
type LegDisconnectedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	Cdr   struct {
		// Disconnect reason. Common SIP failures are mapped to named reasons; unmapped 4xx/5xx/6xx codes appear as sip_{code}. This is an open set — treat an unrecognized value as a new reason rather than an error. Known values: api_hangup, room_deleted, remote_bye, caller_cancel, max_duration, session_expired, rtp_timeout, busy, declined, rejected, unavailable, not_found, forbidden, server_error, ring_timeout, unauthorized, timeout, cancelled, not_acceptable, service_unavailable, invite_failed, connect_failed, challenged, transfer_completed, transfer_originate_failed, transfer_connect_failed, bad_answer, siprec_answer_failed, mixer_panic, hangup, peer_slow, connection_reset, ws_error, ws_dial_failed, moq_error, ice_failure, ice_failed, ice_disconnected, livekit_client_initiated, livekit_duplicate_identity, livekit_server_shutdown, livekit_kicked, livekit_room_deleted, livekit_state_mismatch, livekit_join_failure, livekit_migration, livekit_signal_close, livekit_room_closed, livekit_user_unavailable, livekit_user_rejected, livekit_token_expired, livekit_media_failure, livekit_disconnected, livekit_client_closed, livekit_signal_closed, livekit_signal_error, livekit_pc_setup_failed, livekit_add_track_failed, livekit_publisher_failed, livekit_subscriber_failed, livekit_signal_loop_exit, livekit_set_remote_desc_failed, livekit_create_answer_failed, livekit_set_local_desc_failed, livekit_signal_send_failed, livekit_set_publisher_remote_failed, livekit_participant_left.
		Reason string `json:"reason"`
		// Seconds from leg creation to disconnect.
		DurationTotal float64 `json:"duration_total"`
		// Seconds from answer to disconnect (0 if never answered).
		DurationAnswered float64 `json:"duration_answered"`
	} `json:"cdr,omitempty"`
	// RTP quality metrics. Omitted for WebRTC legs or unanswered legs with no media.
	Quality *struct {
		// Mean Opinion Score (1.0–5.0) estimated via simplified E-model (ITU-T G.107) from packet loss and jitter.
		MosScore float64 `json:"mos_score"`
		// Total inbound RTP audio packets received.
		RtpPacketsReceived int `json:"rtp_packets_received"`
		// Estimated lost packets based on sequence number gaps.
		RtpPacketsLost int `json:"rtp_packets_lost"`
		// Inter-arrival jitter in milliseconds (RFC 3550 §A.8).
		RtpJitterMs float64 `json:"rtp_jitter_ms"`
	} `json:"quality,omitempty"`
}

// LegJoinedRoomEvent is fired when: leg added to a room
type LegJoinedRoomEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
}

// LegLeftRoomEvent is fired when: leg removed from a room
type LegLeftRoomEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
}

// LegMutedEvent is fired when: leg muted
type LegMutedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
}

// LegUnmutedEvent is fired when: leg unmuted
type LegUnmutedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
}

// LegDeafEvent is fired when: leg deafened (stops receiving room audio)
type LegDeafEvent struct {
	Event
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
}

// LegUndeafEvent is fired when: leg undeafened (resumes receiving room audio)
type LegUndeafEvent struct {
	Event
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
}

// LegHoldEvent is fired when: leg put on hold (local or remote)
type LegHoldEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Hold direction: "local" (we put them on hold) or "remote" (they put us on hold).
	LegType string `json:"leg_type,omitempty"`
}

// LegUnholdEvent is fired when: leg taken off hold (local or remote)
type LegUnholdEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Hold direction: "local" or "remote".
	LegType string `json:"leg_type,omitempty"`
}

// LegCommandFailedEvent is fired when: an asynchronous leg command (202 Accepted) failed during execution
type LegCommandFailedEvent struct {
	Event
	LegID   string `json:"leg_id,omitempty"`
	AppID   string `json:"app_id,omitempty"`
	Command string `json:"command,omitempty"`
	Error   string `json:"error,omitempty"`
}

// LegStreamAddedEvent is fired when: an additional m=audio stream was negotiated on a live dialog
type LegStreamAddedEvent struct {
	Event
	LegID     string `json:"leg_id,omitempty"`
	AppID     string `json:"app_id,omitempty"`
	StreamID  string `json:"stream_id,omitempty"`
	Mid       string `json:"mid,omitempty"`
	Direction string `json:"direction,omitempty"`
	Lang      string `json:"lang,omitempty"`
	RoomID    string `json:"room_id,omitempty"`
	Role      string `json:"role,omitempty"`
	Reason    string `json:"reason,omitempty"`
}

// LegStreamRemovedEvent is fired when: an audio stream was disabled with a port-0 re-INVITE; its m-line slot survives as a tombstone
type LegStreamRemovedEvent struct {
	Event
	LegID     string `json:"leg_id,omitempty"`
	AppID     string `json:"app_id,omitempty"`
	StreamID  string `json:"stream_id,omitempty"`
	Mid       string `json:"mid,omitempty"`
	Direction string `json:"direction,omitempty"`
	Lang      string `json:"lang,omitempty"`
	RoomID    string `json:"room_id,omitempty"`
	Role      string `json:"role,omitempty"`
	Reason    string `json:"reason,omitempty"`
}

// LegStreamRejectedEvent is fired when: the peer refused an additional audio stream, or it could not be negotiated; the call is unaffected
type LegStreamRejectedEvent struct {
	Event
	LegID     string `json:"leg_id,omitempty"`
	AppID     string `json:"app_id,omitempty"`
	StreamID  string `json:"stream_id,omitempty"`
	Mid       string `json:"mid,omitempty"`
	Direction string `json:"direction,omitempty"`
	Lang      string `json:"lang,omitempty"`
	RoomID    string `json:"room_id,omitempty"`
	Role      string `json:"role,omitempty"`
	Reason    string `json:"reason,omitempty"`
}

// LegStreamFailedEvent is fired when: an audio stream's media loop failed and the stream was torn down; the call continues on its remaining streams
type LegStreamFailedEvent struct {
	Event
	LegID     string `json:"leg_id,omitempty"`
	AppID     string `json:"app_id,omitempty"`
	StreamID  string `json:"stream_id,omitempty"`
	Mid       string `json:"mid,omitempty"`
	Direction string `json:"direction,omitempty"`
	Lang      string `json:"lang,omitempty"`
	RoomID    string `json:"room_id,omitempty"`
	Role      string `json:"role,omitempty"`
	Reason    string `json:"reason,omitempty"`
}

// LegStreamRoomChangedEvent is fired when: an audio stream was attached to or detached from a room (an empty room_id means detached)
type LegStreamRoomChangedEvent struct {
	Event
	LegID     string `json:"leg_id,omitempty"`
	AppID     string `json:"app_id,omitempty"`
	StreamID  string `json:"stream_id,omitempty"`
	Mid       string `json:"mid,omitempty"`
	Direction string `json:"direction,omitempty"`
	Lang      string `json:"lang,omitempty"`
	RoomID    string `json:"room_id,omitempty"`
	Role      string `json:"role,omitempty"`
	Reason    string `json:"reason,omitempty"`
}

// LegStreamRoleChangedEvent is fired when: an audio stream's routing role changed; the room's allow-sets were recomputed atomically
type LegStreamRoleChangedEvent struct {
	Event
	LegID     string `json:"leg_id,omitempty"`
	AppID     string `json:"app_id,omitempty"`
	StreamID  string `json:"stream_id,omitempty"`
	Mid       string `json:"mid,omitempty"`
	Direction string `json:"direction,omitempty"`
	Lang      string `json:"lang,omitempty"`
	RoomID    string `json:"room_id,omitempty"`
	Role      string `json:"role,omitempty"`
	Reason    string `json:"reason,omitempty"`
}

// SiprecSessionStartedEvent is fired when: an inbound SIPREC recording session was accepted; carries the participants and the stream-to-participant bindings
type SiprecSessionStartedEvent struct {
	Event
	LegID        string            `json:"leg_id,omitempty"`
	AppID        string            `json:"app_id,omitempty"`
	SessionID    string            `json:"session_id,omitempty"`
	DataMode     string            `json:"data_mode,omitempty"`
	Participants []ParticipantInfo `json:"participants,omitempty"`
	Streams      []SIPRECStream    `json:"streams,omitempty"`
}

// SiprecSessionEndedEvent is fired when: a SIPREC recording session ended
type SiprecSessionEndedEvent struct {
	Event
	LegID     string `json:"leg_id,omitempty"`
	AppID     string `json:"app_id,omitempty"`
	SessionID string `json:"session_id,omitempty"`
	Reason    string `json:"reason,omitempty"`
}

// SiprecMetadataUpdatedEvent is fired when: a SIPREC recording session's metadata document was updated on a re-INVITE
type SiprecMetadataUpdatedEvent struct {
	Event
	LegID              string         `json:"leg_id,omitempty"`
	AppID              string         `json:"app_id,omitempty"`
	SessionID          string         `json:"session_id,omitempty"`
	DataMode           string         `json:"data_mode,omitempty"`
	ParticipantsJoined []string       `json:"participants_joined,omitempty"`
	ParticipantsLeft   []string       `json:"participants_left,omitempty"`
	StreamsAdded       []string       `json:"streams_added,omitempty"`
	StreamsRemoved     []string       `json:"streams_removed,omitempty"`
	Streams            []SIPRECStream `json:"streams,omitempty"`
}

// SiprecParticipantJoinedEvent is fired when: a party joined the call being recorded by a SIPREC session
type SiprecParticipantJoinedEvent struct {
	Event
	LegID           string `json:"leg_id,omitempty"`
	AppID           string `json:"app_id,omitempty"`
	SessionID       string `json:"session_id,omitempty"`
	Label           string `json:"label,omitempty"`
	LegStreamID     string `json:"leg_stream_id,omitempty"`
	ParticipantID   string `json:"participant_id,omitempty"`
	ParticipantAor  string `json:"participant_aor,omitempty"`
	ParticipantName string `json:"participant_name,omitempty"`
}

// SiprecParticipantLeftEvent is fired when: a party left the call being recorded by a SIPREC session
type SiprecParticipantLeftEvent struct {
	Event
	LegID           string `json:"leg_id,omitempty"`
	AppID           string `json:"app_id,omitempty"`
	SessionID       string `json:"session_id,omitempty"`
	Label           string `json:"label,omitempty"`
	LegStreamID     string `json:"leg_stream_id,omitempty"`
	ParticipantID   string `json:"participant_id,omitempty"`
	ParticipantAor  string `json:"participant_aor,omitempty"`
	ParticipantName string `json:"participant_name,omitempty"`
}

// DTMFReceivedEvent is fired when: dTMF digit received
type DTMFReceivedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// DTMF digit received.
	Digit string `json:"digit,omitempty"`
	Seq   int    `json:"seq,omitempty"`
}

// RTTReceivedEvent is fired when: real-Time Text (T.140 / RFC 4103) chunk received from the remote
type RTTReceivedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// UTF-8 text chunk received from the remote.
	Text string `json:"text,omitempty"`
	// Per-leg monotonic sequence (independent of RTP sequence numbers).
	Seq int `json:"seq,omitempty"`
	// True when a U+FFFD has been prepended to indicate text was lost beyond what RFC 2198 redundancy could recover.
	LossMarker bool `json:"loss_marker,omitempty"`
}

// SpeakingStartedEvent is fired when: participant started speaking
type SpeakingStartedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier (present only when the leg is in a room).
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
}

// SpeakingStoppedEvent is fired when: participant stopped speaking
type SpeakingStoppedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier (present only when the leg is in a room).
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
}

// PlaybackStartedEvent is fired when: playback began
type PlaybackStartedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Playback identifier.
	PlaybackID string `json:"playback_id,omitempty"`
}

// PlaybackFinishedEvent is fired when: playback ended
type PlaybackFinishedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Playback identifier.
	PlaybackID string `json:"playback_id,omitempty"`
	// Why playback ended: 'completed' (reached the end of the audio) or 'stopped' (did not reach the end, for any reason).
	Reason string `json:"reason,omitempty"`
	// Milliseconds of audio actually played, accumulated across repeat iterations.
	PlayedMs int `json:"played_ms,omitempty"`
}

// PlaybackErrorEvent is fired when: playback failed
type PlaybackErrorEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Playback identifier.
	PlaybackID string `json:"playback_id,omitempty"`
	// Error message.
	Error string `json:"error,omitempty"`
}

// TTSStartedEvent is fired when: tTS synthesis began playing
type TTSStartedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// TTS playback identifier.
	TTSID string `json:"tts_id,omitempty"`
}

// TTSFinishedEvent is fired when: tTS synthesis finished playing
type TTSFinishedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// TTS playback identifier.
	TTSID string `json:"tts_id,omitempty"`
	// Why the utterance ended: 'completed' (reached the end of the audio) or 'stopped' (did not reach the end, for any reason).
	Reason string `json:"reason,omitempty"`
	// Milliseconds of audio actually played.
	PlayedMs int `json:"played_ms,omitempty"`
}

// TTSErrorEvent is fired when: tTS synthesis or playback failed
type TTSErrorEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// TTS playback identifier.
	TTSID string `json:"tts_id,omitempty"`
	// Error message.
	Error string `json:"error,omitempty"`
	// Failure category: permanent_auth, permanent_input, rate_limited, service_unavailable, retryable, canceled or unknown for a synthesis failure, playback for a failure while streaming the audio. New values may be added; treat an unrecognised value as unknown.
	Category string `json:"category,omitempty"`
}

// TTSStagedEvent is fired when: preflight TTS finished synthesizing and is ready to commit
type TTSStagedEvent struct {
	Event
	// Leg identifier.
	LegID  string `json:"leg_id,omitempty"`
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// TTS playback identifier, to commit or discard.
	TTSID string `json:"tts_id,omitempty"`
	// Size of the buffered audio.
	Bytes int `json:"bytes,omitempty"`
	// How long the buffered audio will play for. 0 when the duration is not derivable from the audio format.
	DurationMs int `json:"duration_ms,omitempty"`
}

// TTSDiscardedEvent is fired when: staged TTS was dropped without being played
type TTSDiscardedEvent struct {
	Event
	// Leg identifier.
	LegID  string `json:"leg_id,omitempty"`
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// TTS playback identifier.
	TTSID string `json:"tts_id,omitempty"`
	// Why the staged utterance was dropped: 'app' (explicitly discarded), 'expired' (TTS_PREFLIGHT_TTL elapsed) or 'leg_gone' (the leg ended while it was staged).
	Reason string `json:"reason,omitempty"`
}

// RecordingStartedEvent is fired when: recording began
type RecordingStartedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Recording file path or S3 URI — does not exist yet; the path only appears when the recording stops.
	File string `json:"file,omitempty"`
}

// RecordingFinishedEvent is fired when: recording ended
type RecordingFinishedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Recording file path or S3 URI.
	File             string                 `json:"file,omitempty"`
	MultiChannelFile string                 `json:"multi_channel_file,omitempty"`
	Channels         map[string]ChannelInfo `json:"channels,omitempty"`
	// Participants whose audio is missing from multi_channel_file because their capture failed. Absent when the recording is complete.
	OmittedLegs []string `json:"omitted_legs,omitempty"`
}

// RecordingPausedEvent is fired when: recording paused (audio replaced with silence)
type RecordingPausedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	File   string `json:"file,omitempty"`
}

// RecordingResumedEvent is fired when: recording resumed from a paused state
type RecordingResumedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	File   string `json:"file,omitempty"`
}

// LegTransferInitiatedEvent is fired when: we sent a SIP REFER (transfer initiated by the operator)
type LegTransferInitiatedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Transfer kind: "blind" or "attended".
	Kind string `json:"kind,omitempty"`
	// SIP URI to which the leg is being transferred.
	Target string `json:"target,omitempty"`
	// Leg whose dialog is replaced (attended transfer only).
	ReplacesLegID string `json:"replaces_leg_id,omitempty"`
}

// LegTransferRequestedEvent is fired when: we received a SIP REFER from the peer; decide via accept_transfer/decline_transfer (unless SIP_REFER_AUTO_DIAL=true)
type LegTransferRequestedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Transfer kind: "blind" or "attended".
	Kind string `json:"kind,omitempty"`
	// SIP URI requested by the peer.
	Target string `json:"target,omitempty"`
	// Call-ID present in the Refer-To Replaces parameter (attended only).
	ReplacesCallID string `json:"replaces_call_id,omitempty"`
	// Vestigial (always false); retained for wire compatibility. The outcome now flows via leg.transfer_completed / leg.transfer_failed after the app decides.
	Declined bool `json:"declined,omitempty"`
}

// LegTransferProgressEvent is fired when: transfer progress reported via NOTIFY sipfrag
type LegTransferProgressEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Provisional SIP status from the NOTIFY sipfrag.
	StatusCode int `json:"status_code,omitempty"`
	// Reason phrase.
	Reason string `json:"reason,omitempty"`
}

// LegTransferCompletedEvent is fired when: transfer reached terminal 2xx
type LegTransferCompletedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Final 2xx SIP status from the NOTIFY sipfrag.
	StatusCode int `json:"status_code,omitempty"`
	// Reason phrase.
	Reason string `json:"reason,omitempty"`
}

// LegTransferFailedEvent is fired when: transfer failed (REFER rejected, sipfrag non-2xx, or local error)
type LegTransferFailedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Final non-2xx SIP status (when applicable).
	StatusCode int `json:"status_code,omitempty"`
	// Reason phrase.
	Reason string `json:"reason,omitempty"`
	// Local error message (when no SIP status applies).
	Error string `json:"error,omitempty"`
}

// RoomCreatedEvent is fired when: room created
type RoomCreatedEvent struct {
	Event
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
}

// RoomDeletedEvent is fired when: room deleted
type RoomDeletedEvent struct {
	Event
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
}

// RoomBridgedEvent is fired when: two rooms' mixers were joined
type RoomBridgedEvent struct {
	Event
	// Bridge identifier.
	BridgeID string `json:"bridge_id,omitempty"`
	// First bridged room.
	RoomAID string `json:"room_a_id,omitempty"`
	// Second bridged room.
	RoomBID string `json:"room_b_id,omitempty"`
	AppID   string `json:"app_id,omitempty"`
	// Canonical direction relative to room_a_id: "bidirectional", "a_to_b", "b_to_a", or "none".
	Direction string `json:"direction,omitempty"`
}

// RoomBridgeUpdatedEvent is fired when: a bridge's audio flow direction changed
type RoomBridgeUpdatedEvent struct {
	Event
	// Bridge identifier.
	BridgeID string `json:"bridge_id,omitempty"`
	// First bridged room.
	RoomAID string `json:"room_a_id,omitempty"`
	// Second bridged room.
	RoomBID string `json:"room_b_id,omitempty"`
	AppID   string `json:"app_id,omitempty"`
	// New canonical direction relative to room_a_id.
	Direction string `json:"direction,omitempty"`
}

// RoomUnbridgedEvent is fired when: a bridge was torn down
type RoomUnbridgedEvent struct {
	Event
	// Bridge identifier.
	BridgeID string `json:"bridge_id,omitempty"`
	// First bridged room.
	RoomAID string `json:"room_a_id,omitempty"`
	// Second bridged room.
	RoomBID string `json:"room_b_id,omitempty"`
	AppID   string `json:"app_id,omitempty"`
	// Empty for an explicit delete, or "room_deleted" when a bridged room was deleted.
	Reason string `json:"reason,omitempty"`
}

// RoomRoutingChangedEvent is fired when: the room's audio routing matrix changed
type RoomRoutingChangedEvent struct {
	Event
	RoomID string              `json:"room_id,omitempty"`
	AppID  string              `json:"app_id,omitempty"`
	Matrix map[string][]string `json:"matrix,omitempty"`
	Reason string              `json:"reason,omitempty"`
}

// LegRoleChangedEvent is fired when: a leg's routing role changed
type LegRoleChangedEvent struct {
	Event
	LegID   string `json:"leg_id,omitempty"`
	RoomID  string `json:"room_id,omitempty"`
	AppID   string `json:"app_id,omitempty"`
	OldRole string `json:"old_role,omitempty"`
	NewRole string `json:"new_role,omitempty"`
}

// STTTextEvent is fired when: speech-to-text transcript
type STTTextEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Which of the leg's audio streams this came from. Empty when the leg's audio is the call itself; set for a recording session, where each stream is a different party. Resolve it through GET /v1/legs/{id}/siprec.
	StreamID string `json:"stream_id,omitempty"`
	// Transcribed text.
	Text string `json:"text,omitempty"`
	// Whether this is a final or partial transcript.
	IsFinal bool `json:"is_final,omitempty"`
	// Whether the speaker stopped talking, as opposed to is_final's 'this segment will not change again'. Deepgram only; always false for providers that do not report it.
	SpeechFinal bool `json:"speech_final,omitempty"`
	// Where in the stream this was said, in milliseconds from the first audio the transcriber was given. Absent when the provider reports no timing. Not the same as the event's arrival time, which is when the provider finished rather than when the words were spoken.
	AudioStartMs int `json:"audio_start_ms,omitempty"`
	// End of the span audio_start_ms opens.
	AudioEndMs int `json:"audio_end_ms,omitempty"`
}

// STTTurnEvent is fired when: speech-to-text turn boundary
type STTTurnEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Which of the leg's audio streams this turn belongs to. Empty when the leg's audio is the call itself. See stt.text.stream_id.
	StreamID string `json:"stream_id,omitempty"`
	// Turn boundary: start_of_turn, update, eager_end_of_turn, turn_resumed or end_of_turn (Deepgram Flux), or utterance_end (Deepgram, when utterance_end_ms is set). New values may be added.
	TurnEvent string `json:"event,omitempty"`
	// Index of the turn within the session, incrementing after each end_of_turn.
	TurnIndex int `json:"turn_index,omitempty"`
	// Transcript of the turn so far. Empty on utterance_end.
	Text string `json:"text,omitempty"`
	// How confident the model is that the turn has ended.
	EndOfTurnConfidence float64 `json:"end_of_turn_confidence,omitempty"`
	// Start of the audio window this transcript covers.
	AudioWindowStartMs int `json:"audio_window_start_ms,omitempty"`
	// End of the audio window this transcript covers.
	AudioWindowEndMs int `json:"audio_window_end_ms,omitempty"`
	// When the last word ended (utterance_end only).
	LastWordEndMs int `json:"last_word_end_ms,omitempty"`
	// Per-word transcript with timings and confidence, when the provider supplies it.
	Words []STTWord `json:"words,omitempty"`
	// Languages detected in the turn.
	Languages []string `json:"languages,omitempty"`
}

// AgentConnectedEvent is fired when: agent connected to provider
type AgentConnectedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Provider-assigned conversation identifier.
	ConversationID string `json:"conversation_id,omitempty"`
}

// AgentDisconnectedEvent is fired when: agent session ended
type AgentDisconnectedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
}

// AgentUserTranscriptEvent is fired when: user speech transcribed by agent
type AgentUserTranscriptEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// User speech text.
	Text string `json:"text,omitempty"`
}

// AgentAgentResponseEvent is fired when: agent generated a response
type AgentAgentResponseEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Agent response text.
	Text string `json:"text,omitempty"`
}

// AMDResultEvent is fired when: answering machine detection completed
type AMDResultEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Detection result: human, machine, no_speech, or not_sure.
	Result string `json:"result,omitempty"`
	// Milliseconds of silence before first speech.
	InitialSilenceMs int `json:"initial_silence_ms,omitempty"`
	// Milliseconds of speech in the greeting.
	GreetingDurationMs int `json:"greeting_duration_ms,omitempty"`
	// Total milliseconds of analysis before determination.
	TotalAnalysisMs int `json:"total_analysis_ms,omitempty"`
}

// AMDBeepEvent is fired when: voicemail beep tone detected after machine classification
type AMDBeepEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Milliseconds from machine detection to beep tone detection.
	BeepMs int `json:"beep_ms,omitempty"`
}

// SIPRegistrationAttemptEvent is fired when: inbound REGISTER surfaced for a challenge/accept/reject decision (auto-accepts on consult timeout)
type SIPRegistrationAttemptEvent struct {
	Event
	AppID            string `json:"app_id,omitempty"`
	AttemptID        string `json:"attempt_id,omitempty"`
	Aor              string `json:"aor,omitempty"`
	Contact          string `json:"contact,omitempty"`
	SourceAddress    string `json:"source_address,omitempty"`
	Transport        string `json:"transport,omitempty"`
	UserAgent        string `json:"user_agent,omitempty"`
	CallID           string `json:"call_id,omitempty"`
	HasAuthorization bool   `json:"has_authorization,omitempty"`
}

// SIPRegistrationActiveEvent is fired when: sIP AOR registration created or refreshed (one event per Contact)
type SIPRegistrationActiveEvent struct {
	Event
	AppID string `json:"app_id,omitempty"`
	// Canonical Address of Record (e.g. sip:alice@vb.example).
	Aor string `json:"aor,omitempty"`
	// Contact URI registered by the UA.
	Contact string `json:"contact,omitempty"`
	// Transport-layer socket (ip:port) the REGISTER arrived on.
	Socket string `json:"socket,omitempty"`
	// Transport: udp | tcp | tls.
	Transport string `json:"transport,omitempty"`
	// User-Agent header from the REGISTER, if present.
	UserAgent string `json:"user_agent,omitempty"`
	// Call-ID of the most recent REGISTER.
	CallID string `json:"call_id,omitempty"`
	// Expiry granted to the binding (clamped to SIP_REGISTRATION_MAX_EXPIRES_SECONDS).
	GrantedExpiresSeconds int `json:"granted_expires_seconds,omitempty"`
	// Absolute expiry time (RFC 3339).
	ExpiresAt string `json:"expires_at,omitempty"`
}

// SIPRegistrationExpiredEvent is fired when: sIP AOR registration removed (TTL, explicit unregister, force-delete, or single-binding replacement)
type SIPRegistrationExpiredEvent struct {
	Event
	AppID string `json:"app_id,omitempty"`
	// Canonical Address of Record.
	Aor string `json:"aor,omitempty"`
	// Contact URI that was unbound.
	Contact string `json:"contact,omitempty"`
	// Transport-layer socket that held the binding.
	Socket string `json:"socket,omitempty"`
	// Why the binding was removed: ttl, unregistered, forced, or replaced.
	Reason string `json:"reason,omitempty"`
}

// SIPOutboundRegistrationActiveEvent is fired when: outbound SIP trunk REGISTER accepted (initial or refresh)
type SIPOutboundRegistrationActiveEvent struct {
	Event
	AppID                 string `json:"app_id,omitempty"`
	TrunkID               string `json:"trunk_id,omitempty"`
	Aor                   string `json:"aor,omitempty"`
	Registrar             string `json:"registrar,omitempty"`
	Contact               string `json:"contact,omitempty"`
	GrantedExpiresSeconds int    `json:"granted_expires_seconds,omitempty"`
	ExpiresAt             string `json:"expires_at,omitempty"`
	CallID                string `json:"call_id,omitempty"`
	SourceAddress         string `json:"source_address,omitempty"`
}

// SIPOutboundRegistrationFailedEvent is fired when: outbound SIP trunk REGISTER failed (transport error, non-2xx response, or digest auth rejected)
type SIPOutboundRegistrationFailedEvent struct {
	Event
	AppID      string `json:"app_id,omitempty"`
	TrunkID    string `json:"trunk_id,omitempty"`
	Aor        string `json:"aor,omitempty"`
	Registrar  string `json:"registrar,omitempty"`
	StatusCode int    `json:"status_code,omitempty"`
	Reason     string `json:"reason,omitempty"`
	Error      string `json:"error,omitempty"`
}

// SIPOutboundRegistrationExpiredEvent is fired when: outbound SIP trunk removed (DELETE, shutdown, or refresh failed past granted lifetime)
type SIPOutboundRegistrationExpiredEvent struct {
	Event
	AppID     string `json:"app_id,omitempty"`
	TrunkID   string `json:"trunk_id,omitempty"`
	Aor       string `json:"aor,omitempty"`
	Registrar string `json:"registrar,omitempty"`
	Reason    string `json:"reason,omitempty"`
}

// ParseEvent unmarshals raw JSON into the appropriate typed event struct.
func ParseEvent(data []byte) (interface{}, error) {
	var base Event
	if err := json.Unmarshal(data, &base); err != nil {
		return nil, fmt.Errorf("parse event envelope: %w", err)
	}
	switch base.Type {
	case EventLegRinging:
		var e LegRingingEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegEarlyMedia:
		var e LegEarlyMediaEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegConnected:
		var e LegConnectedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegDisconnected:
		var e LegDisconnectedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegJoinedRoom:
		var e LegJoinedRoomEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegLeftRoom:
		var e LegLeftRoomEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegMuted:
		var e LegMutedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegUnmuted:
		var e LegUnmutedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegDeaf:
		var e LegDeafEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegUndeaf:
		var e LegUndeafEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegHold:
		var e LegHoldEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegUnhold:
		var e LegUnholdEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegCommandFailed:
		var e LegCommandFailedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegStreamAdded:
		var e LegStreamAddedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegStreamRemoved:
		var e LegStreamRemovedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegStreamRejected:
		var e LegStreamRejectedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegStreamFailed:
		var e LegStreamFailedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegStreamRoomChanged:
		var e LegStreamRoomChangedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegStreamRoleChanged:
		var e LegStreamRoleChangedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSiprecSessionStarted:
		var e SiprecSessionStartedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSiprecSessionEnded:
		var e SiprecSessionEndedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSiprecMetadataUpdated:
		var e SiprecMetadataUpdatedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSiprecParticipantJoined:
		var e SiprecParticipantJoinedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSiprecParticipantLeft:
		var e SiprecParticipantLeftEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventDTMFReceived:
		var e DTMFReceivedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRTTReceived:
		var e RTTReceivedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSpeakingStarted:
		var e SpeakingStartedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSpeakingStopped:
		var e SpeakingStoppedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventPlaybackStarted:
		var e PlaybackStartedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventPlaybackFinished:
		var e PlaybackFinishedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventPlaybackError:
		var e PlaybackErrorEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventTTSStarted:
		var e TTSStartedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventTTSFinished:
		var e TTSFinishedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventTTSError:
		var e TTSErrorEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventTTSStaged:
		var e TTSStagedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventTTSDiscarded:
		var e TTSDiscardedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRecordingStarted:
		var e RecordingStartedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRecordingFinished:
		var e RecordingFinishedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRecordingPaused:
		var e RecordingPausedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRecordingResumed:
		var e RecordingResumedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegTransferInitiated:
		var e LegTransferInitiatedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegTransferRequested:
		var e LegTransferRequestedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegTransferProgress:
		var e LegTransferProgressEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegTransferCompleted:
		var e LegTransferCompletedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegTransferFailed:
		var e LegTransferFailedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRoomCreated:
		var e RoomCreatedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRoomDeleted:
		var e RoomDeletedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRoomBridged:
		var e RoomBridgedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRoomBridgeUpdated:
		var e RoomBridgeUpdatedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRoomUnbridged:
		var e RoomUnbridgedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRoomRoutingChanged:
		var e RoomRoutingChangedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegRoleChanged:
		var e LegRoleChangedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSTTText:
		var e STTTextEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSTTTurn:
		var e STTTurnEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventAgentConnected:
		var e AgentConnectedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventAgentDisconnected:
		var e AgentDisconnectedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventAgentUserTranscript:
		var e AgentUserTranscriptEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventAgentAgentResponse:
		var e AgentAgentResponseEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventAMDResult:
		var e AMDResultEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventAMDBeep:
		var e AMDBeepEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSIPRegistrationAttempt:
		var e SIPRegistrationAttemptEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSIPRegistrationActive:
		var e SIPRegistrationActiveEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSIPRegistrationExpired:
		var e SIPRegistrationExpiredEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSIPOutboundRegistrationActive:
		var e SIPOutboundRegistrationActiveEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSIPOutboundRegistrationFailed:
		var e SIPOutboundRegistrationFailedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSIPOutboundRegistrationExpired:
		var e SIPOutboundRegistrationExpiredEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	default:
		return &base, nil
	}
}
