// Code generated by cmd/generate from openapi.yaml. DO NOT EDIT.

package voiceblender

import (
	"encoding/json"
	"fmt"
	"time"
)

// Event is the base envelope for all webhook/WebSocket events.
type Event struct {
	Type       WebhookEventType `json:"type"`
	Timestamp  time.Time        `json:"timestamp"`
	InstanceID string           `json:"instance_id,omitempty"`
}

// LegRingingEvent is fired when: sIP call ringing (inbound or outbound)
type LegRingingEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Leg type (e.g. sip_inbound, sip_outbound).
	LegType string `json:"leg_type,omitempty"`
	// Dialed SIP URI (outbound only).
	URI string `json:"uri,omitempty"`
	// Caller URI (inbound) or From header value (outbound, if set).
	From string `json:"from,omitempty"`
	// Callee URI (inbound only).
	To string `json:"to,omitempty"`
	// X-* custom SIP headers, if present.
	SIPHeaders    map[string]string `json:"sip_headers,omitempty"`
	OfferedCodecs []OfferedCodec    `json:"offered_codecs,omitempty"`
}

// LegEarlyMediaEvent is fired when: outbound leg received 183 Session Progress with SDP; media pipeline active
type LegEarlyMediaEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Leg type (e.g. sip_outbound).
	LegType string `json:"leg_type,omitempty"`
}

// LegConnectedEvent is fired when: leg answered/connected
type LegConnectedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Leg type (e.g. sip_inbound, sip_outbound, webrtc).
	LegType string `json:"leg_type,omitempty"`
}

// LegDisconnectedEvent is fired when: leg hung up (CDR-style nested structure)
type LegDisconnectedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	Cdr   struct {
		// Disconnect reason. Common SIP failures are mapped to named reasons; unmapped 4xx/5xx/6xx codes appear as sip_{code}.
		Reason string `json:"reason"`
		// Seconds from leg creation to disconnect.
		DurationTotal float64 `json:"duration_total"`
		// Seconds from answer to disconnect (0 if never answered).
		DurationAnswered float64 `json:"duration_answered"`
	} `json:"cdr,omitempty"`
	// RTP quality metrics. Omitted for WebRTC legs or unanswered legs with no media.
	Quality *struct {
		// Mean Opinion Score (1.0–5.0) estimated via simplified E-model (ITU-T G.107) from packet loss and jitter.
		MosScore float64 `json:"mos_score"`
		// Total inbound RTP audio packets received.
		RtpPacketsReceived int `json:"rtp_packets_received"`
		// Estimated lost packets based on sequence number gaps.
		RtpPacketsLost int `json:"rtp_packets_lost"`
		// Inter-arrival jitter in milliseconds (RFC 3550 §A.8).
		RtpJitterMs float64 `json:"rtp_jitter_ms"`
	} `json:"quality,omitempty"`
}

// LegJoinedRoomEvent is fired when: leg added to a room
type LegJoinedRoomEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
}

// LegLeftRoomEvent is fired when: leg removed from a room
type LegLeftRoomEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
}

// LegMutedEvent is fired when: leg muted
type LegMutedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
}

// LegUnmutedEvent is fired when: leg unmuted
type LegUnmutedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
}

// LegDeafEvent is fired when: leg deafened (stops receiving room audio)
type LegDeafEvent struct {
	Event
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
}

// LegUndeafEvent is fired when: leg undeafened (resumes receiving room audio)
type LegUndeafEvent struct {
	Event
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
}

// LegHoldEvent is fired when: leg put on hold (local or remote)
type LegHoldEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Hold direction: "local" (we put them on hold) or "remote" (they put us on hold).
	LegType string `json:"leg_type,omitempty"`
}

// LegUnholdEvent is fired when: leg taken off hold (local or remote)
type LegUnholdEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Hold direction: "local" or "remote".
	LegType string `json:"leg_type,omitempty"`
}

// DTMFReceivedEvent is fired when: dTMF digit received
type DTMFReceivedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// DTMF digit received.
	Digit string `json:"digit,omitempty"`
	Seq   int    `json:"seq,omitempty"`
}

// SpeakingStartedEvent is fired when: participant started speaking
type SpeakingStartedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier (present only when the leg is in a room).
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
}

// SpeakingStoppedEvent is fired when: participant stopped speaking
type SpeakingStoppedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier (present only when the leg is in a room).
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
}

// PlaybackStartedEvent is fired when: playback began
type PlaybackStartedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Playback identifier.
	PlaybackID string `json:"playback_id,omitempty"`
}

// PlaybackFinishedEvent is fired when: playback ended
type PlaybackFinishedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Playback identifier.
	PlaybackID string `json:"playback_id,omitempty"`
}

// PlaybackErrorEvent is fired when: playback failed
type PlaybackErrorEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Playback identifier.
	PlaybackID string `json:"playback_id,omitempty"`
	// Error message.
	Error string `json:"error,omitempty"`
}

// TTSStartedEvent is fired when: tTS synthesis began playing
type TTSStartedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// TTS playback identifier.
	TTSID string `json:"tts_id,omitempty"`
}

// TTSFinishedEvent is fired when: tTS synthesis finished playing
type TTSFinishedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// TTS playback identifier.
	TTSID string `json:"tts_id,omitempty"`
}

// TTSErrorEvent is fired when: tTS synthesis or playback failed
type TTSErrorEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// TTS playback identifier.
	TTSID string `json:"tts_id,omitempty"`
	// Error message.
	Error string `json:"error,omitempty"`
}

// RecordingStartedEvent is fired when: recording began
type RecordingStartedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Recording file path or S3 URI.
	File string `json:"file,omitempty"`
}

// RecordingFinishedEvent is fired when: recording ended
type RecordingFinishedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Recording file path or S3 URI.
	File             string                 `json:"file,omitempty"`
	MultiChannelFile string                 `json:"multi_channel_file,omitempty"`
	Channels         map[string]ChannelInfo `json:"channels,omitempty"`
}

// RecordingPausedEvent is fired when: recording paused (audio replaced with silence)
type RecordingPausedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	File   string `json:"file,omitempty"`
}

// RecordingResumedEvent is fired when: recording resumed from a paused state
type RecordingResumedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	File   string `json:"file,omitempty"`
}

// LegTransferInitiatedEvent is fired when: we sent a SIP REFER (transfer initiated by the operator)
type LegTransferInitiatedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Transfer kind: "blind" or "attended".
	Kind string `json:"kind,omitempty"`
	// SIP URI to which the leg is being transferred.
	Target string `json:"target,omitempty"`
	// Leg whose dialog is replaced (attended transfer only).
	ReplacesLegID string `json:"replaces_leg_id,omitempty"`
}

// LegTransferRequestedEvent is fired when: we received a SIP REFER from the peer
type LegTransferRequestedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Transfer kind: "blind" or "attended".
	Kind string `json:"kind,omitempty"`
	// SIP URI requested by the peer.
	Target string `json:"target,omitempty"`
	// Call-ID present in the Refer-To Replaces parameter (attended only).
	ReplacesCallID string `json:"replaces_call_id,omitempty"`
	// True when the REFER was declined (e.g. SIP_REFER_AUTO_DIAL=false).
	Declined bool `json:"declined,omitempty"`
}

// LegTransferProgressEvent is fired when: transfer progress reported via NOTIFY sipfrag
type LegTransferProgressEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Provisional SIP status from the NOTIFY sipfrag.
	StatusCode int `json:"status_code,omitempty"`
	// Reason phrase.
	Reason string `json:"reason,omitempty"`
}

// LegTransferCompletedEvent is fired when: transfer reached terminal 2xx
type LegTransferCompletedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Final 2xx SIP status from the NOTIFY sipfrag.
	StatusCode int `json:"status_code,omitempty"`
	// Reason phrase.
	Reason string `json:"reason,omitempty"`
}

// LegTransferFailedEvent is fired when: transfer failed (REFER rejected, sipfrag non-2xx, or local error)
type LegTransferFailedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Final non-2xx SIP status (when applicable).
	StatusCode int `json:"status_code,omitempty"`
	// Reason phrase.
	Reason string `json:"reason,omitempty"`
	// Local error message (when no SIP status applies).
	Error string `json:"error,omitempty"`
}

// RoomCreatedEvent is fired when: room created
type RoomCreatedEvent struct {
	Event
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
}

// RoomDeletedEvent is fired when: room deleted
type RoomDeletedEvent struct {
	Event
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
}

// STTTextEvent is fired when: speech-to-text transcript
type STTTextEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Transcribed text.
	Text string `json:"text,omitempty"`
	// Whether this is a final or partial transcript.
	IsFinal bool `json:"is_final,omitempty"`
}

// AgentConnectedEvent is fired when: agent connected to provider
type AgentConnectedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Provider-assigned conversation identifier.
	ConversationID string `json:"conversation_id,omitempty"`
}

// AgentDisconnectedEvent is fired when: agent session ended
type AgentDisconnectedEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
}

// AgentUserTranscriptEvent is fired when: user speech transcribed by agent
type AgentUserTranscriptEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// User speech text.
	Text string `json:"text,omitempty"`
}

// AgentAgentResponseEvent is fired when: agent generated a response
type AgentAgentResponseEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	// Room identifier.
	RoomID string `json:"room_id,omitempty"`
	AppID  string `json:"app_id,omitempty"`
	// Agent response text.
	Text string `json:"text,omitempty"`
}

// AMDResultEvent is fired when: answering machine detection completed
type AMDResultEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Detection result: human, machine, no_speech, or not_sure.
	Result string `json:"result,omitempty"`
	// Milliseconds of silence before first speech.
	InitialSilenceMs int `json:"initial_silence_ms,omitempty"`
	// Milliseconds of speech in the greeting.
	GreetingDurationMs int `json:"greeting_duration_ms,omitempty"`
	// Total milliseconds of analysis before determination.
	TotalAnalysisMs int `json:"total_analysis_ms,omitempty"`
}

// AMDBeepEvent is fired when: voicemail beep tone detected after machine classification
type AMDBeepEvent struct {
	Event
	// Leg identifier.
	LegID string `json:"leg_id,omitempty"`
	AppID string `json:"app_id,omitempty"`
	// Milliseconds from machine detection to beep tone detection.
	BeepMs int `json:"beep_ms,omitempty"`
}

// ParseEvent unmarshals raw JSON into the appropriate typed event struct.
func ParseEvent(data []byte) (interface{}, error) {
	var base Event
	if err := json.Unmarshal(data, &base); err != nil {
		return nil, fmt.Errorf("parse event envelope: %w", err)
	}
	switch base.Type {
	case EventLegRinging:
		var e LegRingingEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegEarlyMedia:
		var e LegEarlyMediaEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegConnected:
		var e LegConnectedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegDisconnected:
		var e LegDisconnectedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegJoinedRoom:
		var e LegJoinedRoomEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegLeftRoom:
		var e LegLeftRoomEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegMuted:
		var e LegMutedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegUnmuted:
		var e LegUnmutedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegDeaf:
		var e LegDeafEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegUndeaf:
		var e LegUndeafEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegHold:
		var e LegHoldEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegUnhold:
		var e LegUnholdEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventDTMFReceived:
		var e DTMFReceivedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSpeakingStarted:
		var e SpeakingStartedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSpeakingStopped:
		var e SpeakingStoppedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventPlaybackStarted:
		var e PlaybackStartedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventPlaybackFinished:
		var e PlaybackFinishedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventPlaybackError:
		var e PlaybackErrorEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventTTSStarted:
		var e TTSStartedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventTTSFinished:
		var e TTSFinishedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventTTSError:
		var e TTSErrorEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRecordingStarted:
		var e RecordingStartedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRecordingFinished:
		var e RecordingFinishedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRecordingPaused:
		var e RecordingPausedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRecordingResumed:
		var e RecordingResumedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegTransferInitiated:
		var e LegTransferInitiatedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegTransferRequested:
		var e LegTransferRequestedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegTransferProgress:
		var e LegTransferProgressEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegTransferCompleted:
		var e LegTransferCompletedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventLegTransferFailed:
		var e LegTransferFailedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRoomCreated:
		var e RoomCreatedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventRoomDeleted:
		var e RoomDeletedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventSTTText:
		var e STTTextEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventAgentConnected:
		var e AgentConnectedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventAgentDisconnected:
		var e AgentDisconnectedEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventAgentUserTranscript:
		var e AgentUserTranscriptEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventAgentAgentResponse:
		var e AgentAgentResponseEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventAMDResult:
		var e AMDResultEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	case EventAMDBeep:
		var e AMDBeepEvent
		if err := json.Unmarshal(data, &e); err != nil {
			return nil, err
		}
		return &e, nil
	default:
		return &base, nil
	}
}
