// Code generated by cmd/generate from openapi.yaml. DO NOT EDIT.

package voiceblender

import (
	"context"
	"net/http"
)

// ListLegs list all active legs
func (c *Client) ListLegs(ctx context.Context) ([]Leg, error) {
	var out []Leg
	if err := c.do(ctx, http.MethodGet, "/legs", nil, &out); err != nil {
		return nil, err
	}
	for i := range out {
		out[i].client = c
	}
	return out, nil
}

// CreateLeg originate an outbound SIP call
func (c *Client) CreateLeg(ctx context.Context, req CreateLegRequest) (*Leg, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out Leg
	if err := c.do(ctx, http.MethodPost, "/legs", body, &out); err != nil {
		return nil, err
	}
	out.client = c
	return &out, nil
}

// GetLeg get a single leg
func (c *Client) GetLeg(ctx context.Context, id string) (*Leg, error) {
	var out Leg
	if err := c.do(ctx, http.MethodGet, "/legs/"+id, nil, &out); err != nil {
		return nil, err
	}
	out.client = c
	return &out, nil
}

// Hangup hang up a leg (asynchronous)
func (l *Leg) Hangup(ctx context.Context, req DeleteLegRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodDelete, "/legs/"+l.ID, body, &out)
}

// Answer answer a ringing or early-media inbound SIP leg (asynchronous)
func (l *Leg) Answer(ctx context.Context, req AnswerLegRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/answer", body, &out)
}

// Ring send 180 Ringing on a ringing inbound SIP leg (asynchronous)
func (l *Leg) Ring(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/ring", nil, &out)
}

// EarlyMedia enable early media on a ringing inbound SIP leg (asynchronous)
func (l *Leg) EarlyMedia(ctx context.Context, req EarlyMediaLegRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/early-media", body, &out)
}

// Mute mute a leg
func (l *Leg) Mute(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/mute", nil, &out)
}

// Unmute unmute a leg
func (l *Leg) Unmute(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodDelete, "/legs/"+l.ID+"/mute", nil, &out)
}

// Hold put a SIP call on hold (asynchronous)
func (l *Leg) Hold(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/hold", nil, &out)
}

// Unhold resume a held SIP call (asynchronous)
func (l *Leg) Unhold(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodDelete, "/legs/"+l.ID+"/hold", nil, &out)
}

// Transfer transfer a SIP leg via REFER (asynchronous)
func (l *Leg) Transfer(ctx context.Context, req TransferRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/transfer", body, &out)
}

// SendDTMF send DTMF digits on a leg
func (l *Leg) SendDTMF(ctx context.Context, req DTMFRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/dtmf", body, &out)
}

// EnableDTMF enable DTMF reception on a leg
func (l *Leg) EnableDTMF(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/dtmf/accept", nil, &out)
}

// DisableDTMF disable DTMF reception on a leg
func (l *Leg) DisableDTMF(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/dtmf/reject", nil, &out)
}

// Play start audio playback to a leg
func (l *Leg) Play(ctx context.Context, req PlaybackRequest) (*PlaybackResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out PlaybackResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/play", body, &out)
}

// VolumePlay change the volume of an active leg playback
func (l *Leg) VolumePlay(ctx context.Context, playbackID string, req VolumeRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPatch, "/legs/"+l.ID+"/play/"+playbackID, body, &out)
}

// StopPlay stop audio playback on a leg
func (l *Leg) StopPlay(ctx context.Context, playbackID string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodDelete, "/legs/"+l.ID+"/play/"+playbackID, nil, &out)
}

// PlayTTS synthesize speech and play it on a leg
func (l *Leg) PlayTTS(ctx context.Context, req TTSRequest) (*TTSResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out TTSResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/tts", body, &out)
}

// Record start recording a leg to a WAV file
func (l *Leg) Record(ctx context.Context, req RecordingRequest) (*RecordingResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out RecordingResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/record", body, &out)
}

// StopRecord stop recording a leg
func (l *Leg) StopRecord(ctx context.Context) (*RecordingResponse, error) {
	var out RecordingResponse
	return &out, l.client.do(ctx, http.MethodDelete, "/legs/"+l.ID+"/record", nil, &out)
}

// PauseRecord pause a leg recording
func (l *Leg) PauseRecord(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/record/pause", nil, &out)
}

// ResumeRecord resume a paused leg recording
func (l *Leg) ResumeRecord(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/record/resume", nil, &out)
}

// STT start real-time speech-to-text on a leg
func (l *Leg) STT(ctx context.Context, req STTRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/stt", body, &out)
}

// StopSTT stop speech-to-text on a leg
func (l *Leg) StopSTT(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodDelete, "/legs/"+l.ID+"/stt", nil, &out)
}

// ElevenLabsAgent attach an ElevenLabs ConvAI agent to a leg
func (l *Leg) ElevenLabsAgent(ctx context.Context, req ElevenLabsAgentRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/agent/elevenlabs", body, &out)
}

// VAPIAgent attach a VAPI agent to a leg
func (l *Leg) VAPIAgent(ctx context.Context, req VAPIAgentRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/agent/vapi", body, &out)
}

// PipecatAgent attach a Pipecat bot to a leg
func (l *Leg) PipecatAgent(ctx context.Context, req PipecatAgentRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/agent/pipecat", body, &out)
}

// DeepgramAgent attach a Deepgram Voice Agent to a leg
func (l *Leg) DeepgramAgent(ctx context.Context, req DeepgramAgentRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/agent/deepgram", body, &out)
}

// AgentMessage inject a message into a running agent session on a leg
func (l *Leg) AgentMessage(ctx context.Context, req AgentMessageRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/agent/message", body, &out)
}

// StopAgent detach the agent from a leg
func (l *Leg) StopAgent(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodDelete, "/legs/"+l.ID+"/agent", nil, &out)
}

// StartAMD start answering machine detection on a connected leg
func (l *Leg) StartAMD(ctx context.Context, req AMDParams) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/amd", body, &out)
}
