// Code generated by cmd/generate from openapi.yaml. DO NOT EDIT.

package voiceblender

import (
	"context"
	"net/http"
)

// ListLegs list all active legs
func (c *Client) ListLegs(ctx context.Context) ([]Leg, error) {
	var out []Leg
	return out, c.do(ctx, http.MethodGet, "/legs", nil, &out)
}

// CreateLeg originate an outbound SIP call
func (c *Client) CreateLeg(ctx context.Context, req CreateLegRequest) (*Leg, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out Leg
	return &out, c.do(ctx, http.MethodPost, "/legs", body, &out)
}

// GetLeg get a single leg
func (c *Client) GetLeg(ctx context.Context, id string) (*Leg, error) {
	var out Leg
	return &out, c.do(ctx, http.MethodGet, "/legs/"+id, nil, &out)
}

// DeleteLeg hang up a leg
func (c *Client) DeleteLeg(ctx context.Context, id string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, c.do(ctx, http.MethodDelete, "/legs/"+id, nil, &out)
}

// AnswerLeg answer a ringing or early-media inbound SIP leg
func (c *Client) AnswerLeg(ctx context.Context, id string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/answer", nil, &out)
}

// EarlyMediaLeg enable early media on a ringing inbound SIP leg
func (c *Client) EarlyMediaLeg(ctx context.Context, id string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/early-media", nil, &out)
}

// MuteLeg mute a leg
func (c *Client) MuteLeg(ctx context.Context, id string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/mute", nil, &out)
}

// UnmuteLeg unmute a leg
func (c *Client) UnmuteLeg(ctx context.Context, id string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, c.do(ctx, http.MethodDelete, "/legs/"+id+"/mute", nil, &out)
}

// HoldLeg put a SIP call on hold
func (c *Client) HoldLeg(ctx context.Context, id string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/hold", nil, &out)
}

// UnholdLeg resume a held SIP call
func (c *Client) UnholdLeg(ctx context.Context, id string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, c.do(ctx, http.MethodDelete, "/legs/"+id+"/hold", nil, &out)
}

// SendDTMF send DTMF digits on a leg
func (c *Client) SendDTMF(ctx context.Context, id string, req DTMFRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/dtmf", body, &out)
}

// PlayLeg start audio playback to a leg
func (c *Client) PlayLeg(ctx context.Context, id string, req PlaybackRequest) (*PlaybackResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out PlaybackResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/play", body, &out)
}

// VolumePlayLeg change the volume of an active leg playback
func (c *Client) VolumePlayLeg(ctx context.Context, id string, playbackID string, req VolumeRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPatch, "/legs/"+id+"/play/"+playbackID, body, &out)
}

// StopPlayLeg stop audio playback on a leg
func (c *Client) StopPlayLeg(ctx context.Context, id string, playbackID string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, c.do(ctx, http.MethodDelete, "/legs/"+id+"/play/"+playbackID, nil, &out)
}

// TTSLeg synthesize speech and play it on a leg
func (c *Client) TTSLeg(ctx context.Context, id string, req TTSRequest) (*TTSResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out TTSResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/tts", body, &out)
}

// RecordLeg start recording a leg to a WAV file
func (c *Client) RecordLeg(ctx context.Context, id string, req RecordingRequest) (*RecordingResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out RecordingResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/record", body, &out)
}

// StopRecordLeg stop recording a leg
func (c *Client) StopRecordLeg(ctx context.Context, id string) (*RecordingResponse, error) {
	var out RecordingResponse
	return &out, c.do(ctx, http.MethodDelete, "/legs/"+id+"/record", nil, &out)
}

// STTLeg start real-time speech-to-text on a leg
func (c *Client) STTLeg(ctx context.Context, id string, req STTRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/stt", body, &out)
}

// StopSTTLeg stop speech-to-text on a leg
func (c *Client) StopSTTLeg(ctx context.Context, id string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, c.do(ctx, http.MethodDelete, "/legs/"+id+"/stt", nil, &out)
}

// ElevenLabsAgentLeg attach an ElevenLabs ConvAI agent to a leg
func (c *Client) ElevenLabsAgentLeg(ctx context.Context, id string, req ElevenLabsAgentRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/agent/elevenlabs", body, &out)
}

// VAPIAgentLeg attach a VAPI agent to a leg
func (c *Client) VAPIAgentLeg(ctx context.Context, id string, req VAPIAgentRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/agent/vapi", body, &out)
}

// PipecatAgentLeg attach a Pipecat bot to a leg
func (c *Client) PipecatAgentLeg(ctx context.Context, id string, req PipecatAgentRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/agent/pipecat", body, &out)
}

// DeepgramAgentLeg attach a Deepgram Voice Agent to a leg
func (c *Client) DeepgramAgentLeg(ctx context.Context, id string, req DeepgramAgentRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/agent/deepgram", body, &out)
}

// AgentMessageLeg inject a message into a running agent session on a leg
func (c *Client) AgentMessageLeg(ctx context.Context, id string, req AgentMessageRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/agent/message", body, &out)
}

// StopAgentLeg detach the agent from a leg
func (c *Client) StopAgentLeg(ctx context.Context, id string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, c.do(ctx, http.MethodDelete, "/legs/"+id+"/agent", nil, &out)
}

// StartAMDLeg start answering machine detection on a connected leg
func (c *Client) StartAMDLeg(ctx context.Context, id string, req AMDParams) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/legs/"+id+"/amd", body, &out)
}
