// Code generated by cmd/generate from openapi.yaml. DO NOT EDIT.

package voiceblender

import "encoding/json"

// LegType identifies the type of a voice leg.
type LegType string

const (
	// LegTypeSIPInbound is the "sip_inbound" LegType value.
	LegTypeSIPInbound LegType = "sip_inbound"
	// LegTypeSIPOutbound is the "sip_outbound" LegType value.
	LegTypeSIPOutbound LegType = "sip_outbound"
	// LegTypeWebRTC is the "webrtc" LegType value.
	LegTypeWebRTC LegType = "webrtc"
	// LegTypeWhatsappIn is the "whatsapp_in" LegType value.
	LegTypeWhatsappIn LegType = "whatsapp_in"
	// LegTypeWhatsappOut is the "whatsapp_out" LegType value.
	LegTypeWhatsappOut LegType = "whatsapp_out"
)

// LegState is the current state of a leg.
type LegState string

const (
	// LegStatePending is the "pending" LegState value.
	LegStatePending LegState = "pending"
	// LegStateRinging is the "ringing" LegState value.
	LegStateRinging LegState = "ringing"
	// LegStateEarlyMedia is the "early_media" LegState value.
	LegStateEarlyMedia LegState = "early_media"
	// LegStateConnected is the "connected" LegState value.
	LegStateConnected LegState = "connected"
	// LegStateHeld is the "held" LegState value.
	LegStateHeld LegState = "held"
	// LegStateHungUp is the "hung_up" LegState value.
	LegStateHungUp LegState = "hung_up"
)

// WebhookEventType is the type of a webhook event.
type WebhookEventType string

const (
	// EventLegRinging is the "leg.ringing" WebhookEventType value.
	EventLegRinging WebhookEventType = "leg.ringing"
	// EventLegEarlyMedia is the "leg.early_media" WebhookEventType value.
	EventLegEarlyMedia WebhookEventType = "leg.early_media"
	// EventLegConnected is the "leg.connected" WebhookEventType value.
	EventLegConnected WebhookEventType = "leg.connected"
	// EventLegDisconnected is the "leg.disconnected" WebhookEventType value.
	EventLegDisconnected WebhookEventType = "leg.disconnected"
	// EventLegJoinedRoom is the "leg.joined_room" WebhookEventType value.
	EventLegJoinedRoom WebhookEventType = "leg.joined_room"
	// EventLegLeftRoom is the "leg.left_room" WebhookEventType value.
	EventLegLeftRoom WebhookEventType = "leg.left_room"
	// EventLegMuted is the "leg.muted" WebhookEventType value.
	EventLegMuted WebhookEventType = "leg.muted"
	// EventLegUnmuted is the "leg.unmuted" WebhookEventType value.
	EventLegUnmuted WebhookEventType = "leg.unmuted"
	// EventLegDeaf is the "leg.deaf" WebhookEventType value.
	EventLegDeaf WebhookEventType = "leg.deaf"
	// EventLegUndeaf is the "leg.undeaf" WebhookEventType value.
	EventLegUndeaf WebhookEventType = "leg.undeaf"
	// EventLegHold is the "leg.hold" WebhookEventType value.
	EventLegHold WebhookEventType = "leg.hold"
	// EventLegUnhold is the "leg.unhold" WebhookEventType value.
	EventLegUnhold WebhookEventType = "leg.unhold"
	// EventDTMFReceived is the "dtmf.received" WebhookEventType value.
	EventDTMFReceived WebhookEventType = "dtmf.received"
	// EventSpeakingStarted is the "speaking.started" WebhookEventType value.
	EventSpeakingStarted WebhookEventType = "speaking.started"
	// EventSpeakingStopped is the "speaking.stopped" WebhookEventType value.
	EventSpeakingStopped WebhookEventType = "speaking.stopped"
	// EventPlaybackStarted is the "playback.started" WebhookEventType value.
	EventPlaybackStarted WebhookEventType = "playback.started"
	// EventPlaybackFinished is the "playback.finished" WebhookEventType value.
	EventPlaybackFinished WebhookEventType = "playback.finished"
	// EventPlaybackError is the "playback.error" WebhookEventType value.
	EventPlaybackError WebhookEventType = "playback.error"
	// EventTTSStarted is the "tts.started" WebhookEventType value.
	EventTTSStarted WebhookEventType = "tts.started"
	// EventTTSFinished is the "tts.finished" WebhookEventType value.
	EventTTSFinished WebhookEventType = "tts.finished"
	// EventTTSError is the "tts.error" WebhookEventType value.
	EventTTSError WebhookEventType = "tts.error"
	// EventRecordingStarted is the "recording.started" WebhookEventType value.
	EventRecordingStarted WebhookEventType = "recording.started"
	// EventRecordingFinished is the "recording.finished" WebhookEventType value.
	EventRecordingFinished WebhookEventType = "recording.finished"
	// EventRecordingPaused is the "recording.paused" WebhookEventType value.
	EventRecordingPaused WebhookEventType = "recording.paused"
	// EventRecordingResumed is the "recording.resumed" WebhookEventType value.
	EventRecordingResumed WebhookEventType = "recording.resumed"
	// EventLegTransferInitiated is the "leg.transfer_initiated" WebhookEventType value.
	EventLegTransferInitiated WebhookEventType = "leg.transfer_initiated"
	// EventLegTransferRequested is the "leg.transfer_requested" WebhookEventType value.
	EventLegTransferRequested WebhookEventType = "leg.transfer_requested"
	// EventLegTransferProgress is the "leg.transfer_progress" WebhookEventType value.
	EventLegTransferProgress WebhookEventType = "leg.transfer_progress"
	// EventLegTransferCompleted is the "leg.transfer_completed" WebhookEventType value.
	EventLegTransferCompleted WebhookEventType = "leg.transfer_completed"
	// EventLegTransferFailed is the "leg.transfer_failed" WebhookEventType value.
	EventLegTransferFailed WebhookEventType = "leg.transfer_failed"
	// EventRoomCreated is the "room.created" WebhookEventType value.
	EventRoomCreated WebhookEventType = "room.created"
	// EventRoomDeleted is the "room.deleted" WebhookEventType value.
	EventRoomDeleted WebhookEventType = "room.deleted"
	// EventSTTText is the "stt.text" WebhookEventType value.
	EventSTTText WebhookEventType = "stt.text"
	// EventAgentConnected is the "agent.connected" WebhookEventType value.
	EventAgentConnected WebhookEventType = "agent.connected"
	// EventAgentDisconnected is the "agent.disconnected" WebhookEventType value.
	EventAgentDisconnected WebhookEventType = "agent.disconnected"
	// EventAgentUserTranscript is the "agent.user_transcript" WebhookEventType value.
	EventAgentUserTranscript WebhookEventType = "agent.user_transcript"
	// EventAgentAgentResponse is the "agent.agent_response" WebhookEventType value.
	EventAgentAgentResponse WebhookEventType = "agent.agent_response"
	// EventAMDResult is the "amd.result" WebhookEventType value.
	EventAMDResult WebhookEventType = "amd.result"
	// EventAMDBeep is the "amd.beep" WebhookEventType value.
	EventAMDBeep WebhookEventType = "amd.beep"
)

// ChannelInfo is referenced in the spec but not fully defined; use json.RawMessage to decode.
type ChannelInfo = json.RawMessage

// Leg is a leg.
type Leg struct {
	// Instance identifier.
	InstanceID string `json:"instance_id,omitempty"`
	// Unique leg identifier (UUID).
	ID string `json:"id"`
	// Leg type.
	Type LegType `json:"type"`
	// Leg state.
	State LegState `json:"state"`
	// Room ID if the leg is in a room, empty otherwise.
	RoomID string `json:"room_id,omitempty"`
	// Whether the leg is muted (cannot be heard by others).
	Muted bool `json:"muted"`
	// Whether the leg is deaf (cannot hear others).
	Deaf bool `json:"deaf"`
	// Whether the leg receives DTMF digits broadcast from other legs in the same room. Defaults to true.
	AcceptDTMF bool `json:"accept_dtmf"`
	// Whether the call is on hold (SIP legs only).
	Held bool `json:"held"`
	// Application identifier for event stream filtering.
	AppID string `json:"app_id,omitempty"`
	// X-* headers from the inbound INVITE. Only present on sip_inbound legs.
	SIPHeaders map[string]string `json:"sip_headers,omitempty"`
}

// Room is a room.
type Room struct {
	// Instance identifier.
	InstanceID string `json:"instance_id,omitempty"`
	// Room identifier.
	ID string `json:"id"`
	// Application identifier for event stream filtering.
	AppID string `json:"app_id,omitempty"`
	// Mixer sample rate in Hz (8000, 16000, or 48000).
	SampleRate int `json:"sample_rate"`
	// Legs currently in this room.
	Participants []Leg `json:"participants"`
}
