// Code generated by cmd/generate from openapi.yaml. DO NOT EDIT.

package voiceblender

import (
	"context"
	"net/http"
	"net/url"
)

// ListSIPRegistrations list active SIP AOR registrations
func (c *Client) ListSIPRegistrations(ctx context.Context) (*RegistrationsResponse, error) {
	var out RegistrationsResponse
	return &out, c.do(ctx, http.MethodGet, "/sip/registrations", nil, &out)
}

// DeleteSIPRegistration force-unbind an AOR (or a single contact within it)
func (c *Client) DeleteSIPRegistration(ctx context.Context, aor string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, c.do(ctx, http.MethodDelete, "/sip/registrations/"+url.PathEscape(aor), nil, &out)
}

// ChallengeRegistration challenge a parked inbound REGISTER with a 401 digest auth request
func (c *Client) ChallengeRegistration(ctx context.Context, id string, req ChallengeRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/sip/registrations/attempts/"+id+"/challenge", body, &out)
}

// AcceptRegistration accept a parked inbound REGISTER attempt
func (c *Client) AcceptRegistration(ctx context.Context, id string, req RegistrationAcceptRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/sip/registrations/attempts/"+id+"/accept", body, &out)
}

// RejectRegistration reject a parked inbound REGISTER attempt
func (c *Client) RejectRegistration(ctx context.Context, id string, req RegistrationRejectRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, c.do(ctx, http.MethodPost, "/sip/registrations/attempts/"+id+"/reject", body, &out)
}
