// Code generated by cmd/generate from openapi.yaml. DO NOT EDIT.

package voiceblender

import "encoding/json"

// SIPAuth holds SIP digest authentication credentials.
type SIPAuth struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// CreateLegRequest is a create leg request.
type CreateLegRequest struct {
	// Leg type.
	Type string `json:"type"`
	// SIP URI to dial.
	URI string `json:"uri"`
	// Caller ID — sets the user part of the SIP From header (e.g. "+15551234567", "alice").
	From string `json:"from,omitempty"`
	// SIP Privacy header value (e.g. "id", "none").
	Privacy string `json:"privacy,omitempty"`
	// Seconds to wait for answer; 0 = no timeout.
	RingTimeout int `json:"ring_timeout,omitempty"`
	// Maximum call duration in seconds after connect. Automatically hung up when reached. 0 or omitted = no limit.
	MaxDuration int `json:"max_duration,omitempty"`
	// Codec preference order.
	Codecs []string `json:"codecs,omitempty"`
	// Custom SIP headers to include in the outbound INVITE (e.g. X-Correlation-ID).
	Headers map[string]string `json:"headers,omitempty"`
	// Room ID to auto-add the leg to once media is ready (early_media or connected). If the room does not exist, it is automatically created.
	RoomID string `json:"room_id,omitempty"`
	// SIP digest authentication credentials. If the remote challenges with 401/407, sipgo will retry with these credentials.
	Auth *SIPAuth `json:"auth,omitempty"`
	// Route all events for this leg exclusively to this URL instead of global webhooks.
	WebhookURL string `json:"webhook_url,omitempty"`
	// HMAC-SHA256 signing secret for the per-leg webhook.
	WebhookSecret string `json:"webhook_secret,omitempty"`
}

// DTMFRequest is a d t m f request.
type DTMFRequest struct {
	// DTMF digits to send (0-9, *, #).
	Digits string `json:"digits"`
}

// VolumeRequest is a volume request.
type VolumeRequest struct {
	// Volume adjustment (-8 to 8, ~3dB per step, 0 = unchanged).
	Volume int `json:"volume"`
}

// TTSRequest is a t t s request.
type TTSRequest struct {
	// Text to synthesize.
	Text string `json:"text"`
	// Provider-specific voice identifier. ElevenLabs: voice name or ID. AWS Polly: voice ID (e.g. Joanna, Matthew). Google Cloud: voice name — either full format (e.g. en-US-Neural2-F) or short name for Gemini models (e.g. Achernar, Kore). Deepgram: model name (e.g. aura-2-asteria-en).
	Voice string `json:"voice"`
	// Provider-specific model/engine. ElevenLabs: model ID. AWS Polly: engine (standard, neural, long-form, generative; default neural). Google Cloud: model name (e.g. gemini-2.5-pro-tts, chirp3-hd).
	ModelID string `json:"model_id"`
	// Language code (e.g. "en-US", "pl-pl"). Required for Google Gemini TTS voices that use short names (e.g. Achernar). Auto-extracted from full voice names like en-US-Neural2-F.
	Language string `json:"language,omitempty"`
	// Style/tone instruction for promptable voice models (Google Gemini TTS only). E.g. "Read aloud in a warm, welcoming tone.".
	Prompt string `json:"prompt,omitempty"`
	// Volume adjustment in dB (-8 to 8).
	Volume int `json:"volume"`
	// TTS provider: "elevenlabs" (default), "aws", "google", or "deepgram".
	Provider string `json:"provider,omitempty"`
	// ElevenLabs: API key override (falls back to ELEVENLABS_API_KEY env var). AWS: optional ACCESS_KEY:SECRET_KEY override (falls back to default AWS credential chain). Google Cloud: optional API key override (falls back to Application Default Credentials). Deepgram: API key override (falls back to DEEPGRAM_API_KEY env var).
	APIKey string `json:"api_key,omitempty"`
}

// STTRequest is a s t t request.
type STTRequest struct {
	// Language code (e.g. "en", "es").
	Language string `json:"language"`
	// Emit partial (non-final) transcripts.
	Partial bool `json:"partial"`
	// STT provider: "elevenlabs" (default) or "deepgram".
	Provider string `json:"provider,omitempty"`
	// API key override (falls back to ELEVENLABS_API_KEY or DEEPGRAM_API_KEY env var depending on provider).
	APIKey string `json:"api_key,omitempty"`
}

// DeepgramAgentRequest is a deepgram agent request.
type DeepgramAgentRequest struct {
	// Full Deepgram agent settings object (agent.listen, agent.think, agent.speak, etc.). When omitted, sensible defaults are used (nova-3 STT, gpt-4o-mini LLM, aura-2-asteria-en TTS).
	Settings json.RawMessage `json:"settings,omitempty"`
	// Agent greeting message.
	Greeting string `json:"greeting,omitempty"`
	// Language code (e.g. "en", "es").
	Language string `json:"language,omitempty"`
	// API key override (falls back to DEEPGRAM_API_KEY env var).
	APIKey string `json:"api_key,omitempty"`
}

// ElevenLabsAgentRequest is a eleven labs agent request.
type ElevenLabsAgentRequest struct {
	// ElevenLabs agent ID.
	AgentID string `json:"agent_id"`
	// Override the agent's first message.
	FirstMessage string `json:"first_message,omitempty"`
	// Language code (e.g. "en", "es").
	Language string `json:"language,omitempty"`
	// Key-value pairs passed to the agent as dynamic variables.
	DynamicVariables map[string]string `json:"dynamic_variables,omitempty"`
	// API key override (falls back to ELEVENLABS_API_KEY env var).
	APIKey string `json:"api_key,omitempty"`
}

// PipecatAgentRequest is a pipecat agent request.
type PipecatAgentRequest struct {
	// WebSocket URL of the Pipecat bot (e.g. ws://my-bot:8765).
	WebsocketURL string `json:"websocket_url"`
}

// VAPIAgentRequest is a v a p i agent request.
type VAPIAgentRequest struct {
	// VAPI assistant ID.
	AssistantID string `json:"assistant_id"`
	// Override the agent's first message.
	FirstMessage string `json:"first_message,omitempty"`
	// Key-value pairs passed as VAPI variable values (assistantOverrides.variableValues).
	VariableValues map[string]string `json:"variable_values,omitempty"`
	// API key override (falls back to VAPI_API_KEY env var).
	APIKey string `json:"api_key,omitempty"`
}

// AgentMessageRequest is a agent message request.
type AgentMessageRequest struct {
	// Context or instruction to inject into the running agent session.
	Message string `json:"message"`
}

// RecordingRequest is a recording request.
type RecordingRequest struct {
	// "file" (default) — local disk, "s3" — upload to S3 after recording stops.
	Storage string `json:"storage"`
	// When true, record each participant to a separate mono WAV file in addition to the full mix. Only applies to room recordings.
	MultiChannel bool `json:"multi_channel"`
	// S3 bucket name. Overrides S3_BUCKET env var. Required if env var is not set.
	S3Bucket string `json:"s3_bucket"`
	// AWS region. Overrides S3_REGION env var. Default us-east-1.
	S3Region string `json:"s3_region"`
	// Custom S3 endpoint (MinIO, etc.). Overrides S3_ENDPOINT env var.
	S3Endpoint string `json:"s3_endpoint"`
	// Key prefix (e.g. recordings/). Overrides S3_PREFIX env var.
	S3Prefix string `json:"s3_prefix"`
	// AWS access key ID. Overrides default credential chain.
	S3AccessKey string `json:"s3_access_key"`
	// AWS secret access key. Must be set together with s3_access_key.
	S3SecretKey string `json:"s3_secret_key"`
}

// WebRTCOfferRequest is a web r t c offer request.
type WebRTCOfferRequest struct {
	// SDP offer from the browser.
	SDP string `json:"sdp"`
}

// CreateRoomRequest is a create room request.
type CreateRoomRequest struct {
	// Custom room ID (auto-generated UUID if omitted).
	ID string `json:"id"`
	// Route all events for this room exclusively to this URL instead of global webhooks.
	WebhookURL string `json:"webhook_url,omitempty"`
	// HMAC-SHA256 signing secret for the per-room webhook.
	WebhookSecret string `json:"webhook_secret,omitempty"`
}

// AddLegRequest is a add leg request.
type AddLegRequest struct {
	// ID of the leg to add.
	LegID string `json:"leg_id"`
}

// ICECandidateInit is a WebRTC ICE candidate initialisation struct.
type ICECandidateInit struct {
	Candidate        string  `json:"candidate"`
	SDPMid           *string `json:"sdpMid,omitempty"`
	SDPMLineIndex    *uint16 `json:"sdpMLineIndex,omitempty"`
	UsernameFragment *string `json:"usernameFragment,omitempty"`
}
