// Code generated by cmd/generate from openapi.yaml. DO NOT EDIT.

package voiceblender

import "encoding/json"

// AddLegRequest is a add leg request.
type AddLegRequest struct {
	// ID of the leg to add.
	LegID string `json:"leg_id"`
	// If set, apply this mute state to the leg atomically before it joins the mixer (no race where un-muted audio enters the mix). Omit to leave current state untouched (useful when moving between rooms).
	Mute *bool `json:"mute,omitempty"`
	// If set, apply this deaf state to the leg atomically before it joins the mixer. Omit to leave current state untouched.
	Deaf *bool `json:"deaf,omitempty"`
	// If set, control whether this leg receives DTMF digits broadcast from other legs in the same room. Omit to leave current state untouched (default for new legs is true).
	AcceptDTMF *bool `json:"accept_dtmf,omitempty"`
	// If set, apply this routing role to the leg atomically before it joins the mixer. The room's routing matrix (see PUT /v1/rooms/{id}/routing) decides which other legs this leg hears and is heard by based on roles. Pass "" to clear the role (full mesh). Omit to leave the current role untouched.
	Role string `json:"role,omitempty"`
	// Additional audio streams of the leg to mix into this room, each with its own routing role. Omit to add only the leg's primary stream. A stream already mixed elsewhere is moved here.
	Streams []AddRoomStream `json:"streams,omitempty"`
}

// AddLegStreamRequest is a add leg stream request.
type AddLegStreamRequest struct {
	// Media direction for the new stream, from this server's point of view. Defaults to sendrecv.
	Direction string `json:"direction,omitempty"`
	// BCP 47 language tag advertised as a=lang (RFC 8866), e.g. "es-ES" for a Spanish translation feed.
	Lang string `json:"lang,omitempty"`
	// Value advertised as a=content (RFC 4796). Use "main" for original audio and "alt" for an alternative feed such as a translation.
	Content string `json:"content,omitempty"`
	// Value advertised as a=label (RFC 4574), for correlating the stream with external metadata.
	Label string `json:"label,omitempty"`
	// If set, attach the new stream to this room once it is negotiated.
	RoomID string `json:"room_id,omitempty"`
	// Routing role to apply when room_id is set.
	Role string `json:"role,omitempty"`
}

// AgentMessageRequest is a agent message request.
type AgentMessageRequest struct {
	// Context or instruction to inject into the running agent session.
	Message string `json:"message"`
}

// AnswerLegRequest is a answer leg request.
type AnswerLegRequest struct {
	// If true, emit speaking.started and speaking.stopped events for this leg. If false, suppress them. Omit to use the server default (SPEECH_DETECTION_ENABLED env var, default false).
	SpeechDetection *bool `json:"speech_detection,omitempty"`
	// Explicit codec for the answer SDP. Must appear in the remote offer's offered_codecs list. Omit to use the server's default preference order.
	Codec string `json:"codec,omitempty"`
	// Rooms for the caller's additional audio streams, applied once the answer is negotiated. Positional: entry i addresses the i-th accepted stream beyond the primary, in m-line order — the caller's offer decides how many exist, so an entry with no matching stream is ignored. Use POST /v1/legs/{id}/streams/{streamId}/room to re-route a stream later.
	Streams []AnswerLegStream `json:"streams,omitempty"`
	// Opaque application JSON attached to the leg. Any JSON value is accepted (object, array, string, number, boolean). It is echoed on the leg view and carried at the top level of every event published for this leg, so external state can be correlated without keeping a leg_id lookup table. Capped by CUSTOM_DATA_MAX_BYTES (default 1024 bytes, 0 = unlimited). Omit to leave any existing value untouched; send null to clear it.
	CustomData interface{} `json:"custom_data,omitempty"`
}

// AttachStreamRoomRequest is a attach stream room request.
type AttachStreamRoomRequest struct {
	// Room to mix this stream into. May differ from the leg's own room.
	RoomID string `json:"room_id"`
	// Routing role for the stream inside that room. The room's routing matrix decides who hears it.
	Role string `json:"role,omitempty"`
}

// ChallengeRequest is a challenge request.
type ChallengeRequest struct {
	Realm      string   `json:"realm"`
	Username   string   `json:"username,omitempty"`
	Password   string   `json:"password,omitempty"`
	Ha1        string   `json:"ha1,omitempty"`
	Algorithm  string   `json:"algorithm,omitempty"`
	Qop        []string `json:"qop,omitempty"`
	MaxExpires int      `json:"max_expires,omitempty"`
}

// CreateLegRequest is a create leg request.
type CreateLegRequest struct {
	// Leg type.
	Type string `json:"type"`
	// Destination. For sip legs, a SIP URI (e.g. "sip:alice@example.com"); a "sips:" URI or a ";transport=tls" param sends the INVITE over TLS, and ";transport=tcp" over TCP. For whatsapp legs, an E.164 phone number (with or without '+').
	To string `json:"to,omitempty"`
	// Deprecated alias for `to` (sip legs only). Prefer `to`.
	URI string `json:"uri,omitempty"`
	// Caller ID. A bare user-part (e.g. "+15551234567", "alice") sets the user of the SIP From header. A full SIP URI (e.g. "sip:alice@pbx.example.com") sets both the user and the host; otherwise the host comes from the matched trunk's AOR realm, falling back to SIP_DOMAIN.
	From string `json:"from,omitempty"`
	// Next-hop SIP proxy for this INVITE, attached as a loose "Route" header (the Request-URI is left unchanged). Overrides the matched trunk's outbound_proxy and SIP_OUTBOUND_PROXY. Ignored when "to" resolves to an AOR registered to this server, which is delivered to the registered contact instead. SIP legs only.
	OutboundProxy string `json:"outbound_proxy,omitempty"`
	// SIP Privacy header value (e.g. "id", "none").
	Privacy string `json:"privacy,omitempty"`
	// Seconds to wait for answer; 0 = no timeout.
	RingTimeout int `json:"ring_timeout,omitempty"`
	// Maximum call duration in seconds after connect. Automatically hung up when reached. 0 or omitted = no limit.
	MaxDuration int `json:"max_duration,omitempty"`
	// Codec preference order (sip legs only).
	Codecs []string `json:"codecs,omitempty"`
	// Custom headers to include in the outbound INVITE (sip/whatsapp) or the WebSocket upgrade request (websocket).
	Headers map[string]string `json:"headers,omitempty"`
	// Room ID to auto-add the leg to once media is ready (early_media or connected). If the room does not exist, it is automatically created.
	RoomID string `json:"room_id,omitempty"`
	// Digest auth credentials. Required for whatsapp legs (Meta-issued password; username defaults to `from` with '+' stripped). Optional for sip legs (sipgo retries on 401/407 challenge).
	Auth *SIPAuth `json:"auth,omitempty"`
	// Route all events for this leg exclusively to this URL instead of global webhooks.
	WebhookURL string `json:"webhook_url,omitempty"`
	// HMAC-SHA256 signing secret for the per-leg webhook.
	WebhookSecret string `json:"webhook_secret,omitempty"`
	// Enable Answering Machine Detection on outbound calls. Include the object (even empty) to enable with defaults; omit to disable.
	AMD *AMDParams `json:"amd,omitempty"`
	// If false, this leg will not receive DTMF digits broadcast from other legs in the same room. Defaults to true.
	AcceptDTMF *bool `json:"accept_dtmf,omitempty"`
	// Application identifier. Carried through to all events for this leg. Use to filter the WebSocket event stream by app.
	AppID string `json:"app_id,omitempty"`
	// If true, emit speaking.started and speaking.stopped events for this leg. If false, suppress them. Omit to use the server default (SPEECH_DETECTION_ENABLED env var, default false).
	SpeechDetection *bool `json:"speech_detection,omitempty"`
	// For sip legs: offer Real-Time Text (ITU-T T.140 over RTP per RFC 4103) alongside audio. For websocket legs: enable the bidirectional text-message channel. Default: false.
	RTT bool `json:"rtt,omitempty"`
	// Opaque application JSON attached to the leg. Any JSON value is accepted (object, array, string, number, boolean). It is echoed on the leg view and carried at the top level of every event published for this leg, so external state can be correlated without keeping a leg_id lookup table. Capped by CUSTOM_DATA_MAX_BYTES (default 1024 bytes, 0 = unlimited).
	CustomData interface{} `json:"custom_data,omitempty"`
	// SIP outbound only. Extra m=audio sections to offer alongside the call's primary bidirectional audio, so a multi-stream call is established by the first INVITE instead of a follow-up re-INVITE. Each entry binds its own RTP port and may be mixed into its own room. To add a stream to a call that is already up, use POST /v1/legs/{id}/streams instead.
	Streams []CreateLegStream `json:"streams,omitempty"`
	// WebSocket target URL (ws:// or wss://) for outbound websocket legs. Required when type=websocket.
	URL string `json:"url,omitempty"`
	// PCM sample rate for websocket legs. The room's mixer automatically resamples between this and the room rate.
	SampleRate int `json:"sample_rate,omitempty"`
	// Audio framing for websocket legs. `binary` ships raw PCM as WebSocket binary frames; `json_base64` wraps PCM as `{"type":"audio","audio":"<base64>"}` text frames (browser-friendly).
	WireFormat string `json:"wire_format,omitempty"`
	// On-the-wire PCM sample encoding for websocket legs. v1 only supports `s16le`.
	SampleFormat string `json:"sample_format,omitempty"`
	// LiveKit room join parameters (only used when type=livekit_room).
	Livekit *LiveKitParams `json:"livekit,omitempty"`
}

// CreateRoomBridgeRequest is a create room bridge request.
type CreateRoomBridgeRequest struct {
	// Custom bridge ID (auto-generated UUID if omitted).
	ID string `json:"id,omitempty"`
	// The other room to join. Must use the same sample rate as the room in the path.
	RoomID string `json:"room_id"`
	// Audio flow relative to the room in the path: bidirectional (both hear each other), send (path room → other only), receive (other → path room only), none (allocated but silent). Default: bidirectional.
	Direction string `json:"direction,omitempty"`
}

// CreateRoomRequest is a create room request.
type CreateRoomRequest struct {
	// Custom room ID (auto-generated UUID if omitted).
	ID string `json:"id"`
	// Route all events for this room exclusively to this URL instead of global webhooks.
	WebhookURL string `json:"webhook_url,omitempty"`
	// HMAC-SHA256 signing secret for the per-room webhook.
	WebhookSecret string `json:"webhook_secret,omitempty"`
	// Application identifier. Carried through to all events for this room. Use to filter the WebSocket event stream by app.
	AppID string `json:"app_id,omitempty"`
	// Mixer sample rate in Hz. Allowed values: 8000, 16000, 48000. Default: 16000.
	SampleRate int `json:"sample_rate,omitempty"`
}

// CreateTrunkRequest is a create trunk request.
type CreateTrunkRequest struct {
	// Trunk type discriminator. Only `sip_register` is implemented today; `ip_ip` is reserved and returns 501.
	Type string `json:"type"`
	// Application identifier carried through to every event emitted by this trunk.
	AppID string `json:"app_id,omitempty"`
	// Required when type == "sip_register". Configures the outbound REGISTER (registrar URI, AOR, digest credentials, expiry).
	SIPRegister *SIPRegisterTrunkSpec `json:"sip_register,omitempty"`
	// Reserved for static-IP peering (no REGISTER). Not yet implemented; supplying this returns 501.
	IpIp *IPIPTrunkSpec `json:"ip_ip,omitempty"`
}

// DTMFRequest is a DTMF request.
type DTMFRequest struct {
	// DTMF digits to send (0-9, *, #).
	Digits string `json:"digits"`
}

// DeepgramAgentRequest is a deepgram agent request.
type DeepgramAgentRequest struct {
	// Full Deepgram agent settings object (agent.listen, agent.think, agent.speak, etc.). When omitted, sensible defaults are used (nova-3 STT, gpt-4o-mini LLM, aura-2-asteria-en TTS).
	Settings json.RawMessage `json:"settings,omitempty"`
	// Agent greeting message.
	Greeting string `json:"greeting,omitempty"`
	// Language code (e.g. "en", "es").
	Language string `json:"language,omitempty"`
	// API key override (falls back to DEEPGRAM_API_KEY env var).
	APIKey string `json:"api_key,omitempty"`
}

// DeleteLegRequest is a delete leg request.
type DeleteLegRequest struct {
	// Disconnect reason. Only honored for unanswered SIP inbound legs (state `ringing` or `early_media`); on connected legs the body is ignored and the leg is hung up with the legacy `api_hangup` reason. The value flows through to `leg.disconnected`'s `cdr.reason` and selects the SIP final response: `busy`→486, `declined`/`rejected`→603, `unavailable`→480, `not_found`→404, `forbidden`→403, `server_error`→500.
	Reason string `json:"reason,omitempty"`
}

// EarlyMediaLegRequest is a early media leg request.
type EarlyMediaLegRequest struct {
	// Explicit codec for the 183 Session Progress SDP. Must appear in the remote offer's offered_codecs list. Omit to use the server's default preference order.
	Codec string `json:"codec,omitempty"`
	// Opaque application JSON attached to the leg. Any JSON value is accepted (object, array, string, number, boolean). It is echoed on the leg view and carried at the top level of every event published for this leg, so external state can be correlated without keeping a leg_id lookup table. Capped by CUSTOM_DATA_MAX_BYTES (default 1024 bytes, 0 = unlimited). Omit to leave any existing value untouched; send null to clear it.
	CustomData interface{} `json:"custom_data,omitempty"`
}

// ElevenLabsAgentRequest is a eleven labs agent request.
type ElevenLabsAgentRequest struct {
	// ElevenLabs agent ID.
	AgentID string `json:"agent_id"`
	// Override the agent's first message.
	FirstMessage string `json:"first_message,omitempty"`
	// Language code (e.g. "en", "es").
	Language string `json:"language,omitempty"`
	// Key-value pairs passed to the agent as dynamic variables.
	DynamicVariables map[string]string `json:"dynamic_variables,omitempty"`
	// API key override (falls back to ELEVENLABS_API_KEY env var).
	APIKey string `json:"api_key,omitempty"`
}

// PipecatAgentRequest is a pipecat agent request.
type PipecatAgentRequest struct {
	// WebSocket URL of the Pipecat bot (e.g. ws://my-bot:8765).
	WebsocketURL string `json:"websocket_url"`
}

// RTTRequest is a RTT request.
type RTTRequest struct {
	// UTF-8 text to send. May be one or more characters and may include T.140 control codes (e.g. backspace U+0008, CR/LF).
	Text string `json:"text"`
}

// RecordingRequest is a recording request.
type RecordingRequest struct {
	// "file" (default) — local disk, "s3" — upload to S3 after recording stops, "gcs" — upload to Google Cloud Storage via the native GCS API (Application Default Credentials / Workload Identity).
	Storage string `json:"storage"`
	// When true, record each participant to a separate mono WAV file in addition to the full mix. Only applies to room recordings.
	MultiChannel bool `json:"multi_channel"`
	// S3 bucket name. Overrides S3_BUCKET env var. Required if env var is not set.
	S3Bucket string `json:"s3_bucket"`
	// AWS region. Overrides S3_REGION env var. Default us-east-1.
	S3Region string `json:"s3_region"`
	// Custom S3 endpoint (MinIO, etc.). Overrides S3_ENDPOINT env var.
	S3Endpoint string `json:"s3_endpoint"`
	// Key prefix (e.g. recordings/). Overrides S3_PREFIX env var.
	S3Prefix string `json:"s3_prefix"`
	// AWS access key ID. Overrides default credential chain.
	S3AccessKey string `json:"s3_access_key"`
	// AWS secret access key. Must be set together with s3_access_key.
	S3SecretKey string `json:"s3_secret_key"`
	// GCS bucket name. Overrides GCS_BUCKET env var. Required if env var is not set when storage=gcs.
	GcsBucket string `json:"gcs_bucket"`
	// Object name prefix (e.g. recordings or recordings/). Overrides GCS_OBJECT_NAME_PREFIX env var. A trailing slash is added automatically when missing.
	GcsObjectNamePrefix string `json:"gcs_object_name_prefix"`
	// Optional output basename for the WAV file. A .wav suffix is added when missing. Must be a single path segment (no directories). Dots inside the name are preserved (only a trailing .wav is treated as the extension). Rejected with 409 if the file already exists or another recording is using the same name. When omitted, a timestamped name is generated.
	Filename string `json:"filename"`
}

// RegistrationAcceptRequest is a registration accept request.
type RegistrationAcceptRequest struct {
	MaxExpires int `json:"max_expires,omitempty"`
}

// RegistrationRejectRequest is a registration reject request.
type RegistrationRejectRequest struct {
	Code   int    `json:"code,omitempty"`
	Reason string `json:"reason,omitempty"`
}

// RingLegRequest is a ring leg request.
type RingLegRequest struct {
	// Opaque application JSON attached to the leg. Any JSON value is accepted (object, array, string, number, boolean). It is echoed on the leg view and carried at the top level of every event published for this leg, so external state can be correlated without keeping a leg_id lookup table. Capped by CUSTOM_DATA_MAX_BYTES (default 1024 bytes, 0 = unlimited). Omit to leave any existing value untouched; send null to clear it.
	CustomData interface{} `json:"custom_data,omitempty"`
}

// RoomRoutingRequest is a room routing request.
type RoomRoutingRequest struct {
	// Listener-role → list of allowed source roles. Omitted listener roles default to full mesh. Empty list = hears nothing.
	Matrix map[string][]string `json:"matrix"`
}

// RoomRoutingUpdateRequest is a room routing update request.
type RoomRoutingUpdateRequest struct {
	// Per-listener-role row replacements applied as a single atomic update.
	Updates []RoutingRowUpdate `json:"updates"`
}

// STTRequest is a STT request.
type STTRequest struct {
	// Language code (e.g. "en", "es").
	Language string `json:"language"`
	// Emit partial (non-final) transcripts.
	Partial bool `json:"partial"`
	// STT provider: "elevenlabs" (default), "deepgram" (/v1/listen), "deepgram_flux" (/v2/listen, conversational turn detection), "azure" or "speechmatics".
	Provider string `json:"provider,omitempty"`
	// API key override (falls back to ELEVENLABS_API_KEY, DEEPGRAM_API_KEY, AZURE_SPEECH_KEY or SPEECHMATICS_API_KEY env var depending on provider).
	APIKey string `json:"api_key,omitempty"`
	// Provider-specific model. Deepgram: default "nova-3". Deepgram Flux: "flux-general-en" (default) or "flux-general-multi". Speechmatics: "standard" (default) or "enhanced".
	Model string `json:"model,omitempty"`
	// Terms to boost recognition of (Deepgram, Deepgram Flux, and Speechmatics — where they become additional_vocab).
	Keyterms []string `json:"keyterms,omitempty"`
	// Deepgram: milliseconds of silence before a segment is finalized; 0 disables endpointing. Speechmatics: maps to max_delay, clamped to 700-4000 ms; 0 leaves the provider default.
	Endpointing int `json:"endpointing,omitempty"`
	// Deepgram: milliseconds of silence after which an stt.turn event with event=utterance_end is emitted. Deepgram requires interim results for this, which are requested automatically and still suppressed unless partial is true. Speechmatics: milliseconds of silence that close a turn and emit an stt.turn event with event=end_of_turn — default 600, capped at 2000, and 0 disables turn detection.
	UtteranceEndMs int `json:"utterance_end_ms,omitempty"`
	// Deepgram Flux only: end-of-turn confidence that fires an eager_end_of_turn stt.turn event, enabling speculative generation. Must be between 0.3 and 0.9. When unset, no eager_end_of_turn or turn_resumed events are emitted at all.
	EagerEotThreshold float64 `json:"eager_eot_threshold,omitempty"`
	// Deepgram Flux only: end-of-turn confidence required to close a turn. Deepgram default 0.7.
	EotThreshold float64 `json:"eot_threshold,omitempty"`
	// Deepgram Flux only: milliseconds of silence after which a turn is closed regardless of confidence. Deepgram default 5000.
	EotTimeoutMs int `json:"eot_timeout_ms,omitempty"`
	// Deepgram Flux only: candidate language codes for the "flux-general-multi" model.
	LanguageHints []string `json:"language_hints,omitempty"`
}

// SetLegCustomDataRequest is a set leg custom data request.
type SetLegCustomDataRequest struct {
	// New opaque application JSON for the leg. Any JSON value is accepted (object, array, string, number, boolean). Replaces the existing value outright — there is no merge. Sending null clears it, the same as DELETE. Required: omitting the field is rejected with 400. Capped by CUSTOM_DATA_MAX_BYTES (default 1024 bytes, 0 = unlimited).
	CustomData interface{} `json:"custom_data"`
}

// SetLegRoleRequest is a set leg role request.
type SetLegRoleRequest struct {
	// New routing role for the leg. The room's routing matrix decides which other legs this leg hears and is heard by based on roles. Pass an empty string to clear the role (full mesh).
	Role string `json:"role"`
}

// StartSIPRECRequest is a start SIPREC request.
type StartSIPRECRequest struct {
	// SIP URI of the session recording server, e.g. "sip:srs@recorder.example.com:5060;transport=tcp". A recording session carries the metadata document alongside the SDP and exceeds the UDP message limit, so the target should accept TCP. The transport comes from the URI: ";transport=tcp", or "sips:" / ";transport=tls" for TLS.
	SrsURI string `json:"srs_uri"`
	// Which participants to record. Each entry is either a leg ID (that leg's own audio) or "<legID>#<streamID>" for one of a leg's secondary audio streams mixed into the room. Empty or absent records every participant. An entry that is not in the room is a 404.
	LegIds []string `json:"leg_ids,omitempty"`
	// Communication session identifier put in the recording metadata. Defaults to the room ID.
	SessionID string `json:"session_id,omitempty"`
	// Application identifier tagged onto the resulting leg and its events.
	AppID string `json:"app_id,omitempty"`
	// SIP digest username, when the recording server challenges the INVITE.
	AuthUsername string `json:"auth_username,omitempty"`
	// SIP digest password, when the recording server challenges the INVITE.
	AuthPassword string `json:"auth_password,omitempty"`
	// Extra SIP headers to include in the INVITE. Require: siprec is always sent.
	Headers map[string]string `json:"headers,omitempty"`
}

// TTSRequest is a TTS request.
type TTSRequest struct {
	// Text to synthesize.
	Text string `json:"text"`
	// Provider-specific voice identifier. ElevenLabs: voice name or ID. AWS Polly: voice ID (e.g. Joanna, Matthew). Google Cloud: voice name — either full format (e.g. en-US-Neural2-F) or short name for Gemini models (e.g. Achernar, Kore). Deepgram: model name (e.g. aura-2-asteria-en).
	Voice string `json:"voice"`
	// Provider-specific model/engine. ElevenLabs: model ID. AWS Polly: engine (standard, neural, long-form, generative; default neural). Google Cloud: model name (e.g. gemini-2.5-pro-tts, chirp3-hd).
	ModelID string `json:"model_id"`
	// Language code (e.g. "en-US", "pl-pl"). Required for Google Gemini TTS voices that use short names (e.g. Achernar). Auto-extracted from full voice names like en-US-Neural2-F.
	Language string `json:"language,omitempty"`
	// Style/tone instruction for promptable voice models (Google Gemini TTS only). E.g. "Read aloud in a warm, welcoming tone.".
	Prompt string `json:"prompt,omitempty"`
	// Volume adjustment in dB (-8 to 8).
	Volume int `json:"volume"`
	// TTS provider: "elevenlabs" (default), "aws", "google", or "deepgram".
	Provider string `json:"provider,omitempty"`
	// ElevenLabs: API key override (falls back to ELEVENLABS_API_KEY env var). AWS: optional ACCESS_KEY:SECRET_KEY override (falls back to default AWS credential chain). Google Cloud: optional API key override (falls back to Application Default Credentials). Deepgram: API key override (falls back to DEEPGRAM_API_KEY env var).
	APIKey string `json:"api_key,omitempty"`
}

// TransferCompleteRequest is a transfer complete request.
type TransferCompleteRequest struct {
	Success    bool   `json:"success"`
	StatusCode int    `json:"status_code,omitempty"`
	Reason     string `json:"reason,omitempty"`
}

// TransferDeclineRequest is a transfer decline request.
type TransferDeclineRequest struct {
	Code   int    `json:"code,omitempty"`
	Reason string `json:"reason,omitempty"`
}

// TransferProgressRequest is a transfer progress request.
type TransferProgressRequest struct {
	StatusCode int    `json:"status_code"`
	Reason     string `json:"reason,omitempty"`
}

// TransferRequest is a transfer request.
type TransferRequest struct {
	// SIP URI to transfer the call to (e.g. "sip:bob@example.com").
	Target string `json:"target"`
	// ID of an existing connected SIP leg whose dialog should be replaced (attended transfer). Omit for blind transfer.
	ReplacesLegID string `json:"replaces_leg_id,omitempty"`
}

// UpdateLegStreamRequest is a update leg stream request.
type UpdateLegStreamRequest struct {
	// New routing role for this stream inside its room. The room's routing matrix decides who hears it. Pass an empty string to clear the role (full mesh). Omit to leave it untouched. Applied atomically — the room's allow-sets are recomputed in a single mixer-mutex acquisition, so no audio bleeds through mid-change.
	Role string `json:"role,omitempty"`
}

// UpdateRoomBridgeRequest is a update room bridge request.
type UpdateRoomBridgeRequest struct {
	// New audio flow relative to the room in the path: bidirectional, send, receive, or none.
	Direction string `json:"direction"`
}

// VAPIAgentRequest is a VAPI agent request.
type VAPIAgentRequest struct {
	// VAPI assistant ID.
	AssistantID string `json:"assistant_id"`
	// Override the agent's first message.
	FirstMessage string `json:"first_message,omitempty"`
	// Key-value pairs passed as VAPI variable values (assistantOverrides.variableValues).
	VariableValues map[string]string `json:"variable_values,omitempty"`
	// API key override (falls back to VAPI_API_KEY env var).
	APIKey string `json:"api_key,omitempty"`
}

// VolumeRequest is a volume request.
type VolumeRequest struct {
	// Volume adjustment (-8 to 8, ~3dB per step, 0 = unchanged).
	Volume int `json:"volume"`
}

// WebRTCOfferRequest is a web RTC offer request.
type WebRTCOfferRequest struct {
	// SDP offer from the browser.
	SDP string `json:"sdp"`
	// Application identifier. Carried through to all events emitted for this leg, and matched against the VSI `app_id` filter.
	AppID string `json:"app_id,omitempty"`
	// Opaque application JSON attached to the leg. Any JSON value is accepted (object, array, string, number, boolean). It is echoed on the leg view and carried at the top level of every event published for this leg, so external state can be correlated without keeping a leg_id lookup table. Capped by CUSTOM_DATA_MAX_BYTES (default 1024 bytes, 0 = unlimited).
	CustomData interface{} `json:"custom_data,omitempty"`
}

// AMDParams is a AMD params.
type AMDParams struct {
	// Max milliseconds of silence before declaring no_speech.
	InitialSilenceTimeout int `json:"initial_silence_timeout,omitempty"`
	// Speech duration threshold (ms) above which answerer is classified as machine.
	GreetingDuration int `json:"greeting_duration,omitempty"`
	// Silence duration (ms) after initial speech to declare human.
	AfterGreetingSilence int `json:"after_greeting_silence,omitempty"`
	// Max analysis window in milliseconds. A threshold longer than this window suppresses that verdict; a window shorter than all of initial_silence_timeout, greeting_duration and after_greeting_silence is rejected, since the call could only end not_sure.
	TotalAnalysisTime int `json:"total_analysis_time,omitempty"`
	// Minimum speech burst duration (ms) to count as a word.
	MinimumWordLength int `json:"minimum_word_length,omitempty"`
	// Max time (ms) to wait for the voicemail beep after machine detection. 0 or omitted = disabled.
	BeepTimeout int `json:"beep_timeout,omitempty"`
}

// AddRoomStream is a add room stream.
type AddRoomStream struct {
	// Stream identifier from GET /v1/legs/{id}/streams. The primary stream is not addressable here — it joins with the leg itself.
	StreamID string `json:"stream_id"`
	// Routing role for this stream inside the room.
	Role string `json:"role,omitempty"`
}

// AnswerLegStream is a answer leg stream.
type AnswerLegStream struct {
	// Room to mix this stream into once the answer is negotiated. May differ from the room the leg itself joins.
	RoomID string `json:"room_id,omitempty"`
	// Routing role for this stream inside its room.
	Role string `json:"role,omitempty"`
}

// BridgeView is a bridge view.
type BridgeView struct {
	// Bridge identifier.
	ID string `json:"id"`
	// The peer room joined to the room in the path.
	RoomID string `json:"room_id"`
	// Audio flow relative to the room in the path: bidirectional, send, receive, or none.
	Direction string `json:"direction"`
	// Shared mixer sample rate in Hz (both rooms must match).
	SampleRate int `json:"sample_rate"`
}

// ChannelInfo is a channel info.
type ChannelInfo struct {
	Channel int `json:"channel"`
	StartMs int `json:"start_ms"`
	EndMs   int `json:"end_ms"`
}

// CreateLegStream is a create leg stream.
type CreateLegStream struct {
	// Media direction for this stream, from this server's point of view. Defaults to sendrecv.
	Direction string `json:"direction,omitempty"`
	// BCP 47 language tag advertised as a=lang (RFC 8866), e.g. "es-ES" for a Spanish translation feed.
	Lang string `json:"lang,omitempty"`
	// Value advertised as a=content (RFC 4796). Use "alt" for an alternative feed such as a translation.
	Content string `json:"content,omitempty"`
	// Value advertised as a=label (RFC 4574), for correlating the stream with external metadata.
	Label string `json:"label,omitempty"`
	// Room to mix this stream into once the call connects. May differ from the leg's own room_id, which governs the primary stream.
	RoomID string `json:"room_id,omitempty"`
	// Routing role for this stream inside its room.
	Role string `json:"role,omitempty"`
}

// CreateTrunkResponse is a create trunk response.
type CreateTrunkResponse struct {
	ID     string `json:"id"`
	Type   string `json:"type"`
	Status string `json:"status"`
}

// IPIPTrunkSpec is a IPIP trunk spec.
type IPIPTrunkSpec struct {
	// Static peer SIP URI for IP-IP peering. Reserved; not yet implemented.
	PeerURI string `json:"peer_uri,omitempty"`
}

// IPIPTrunkView is a IPIP trunk view.
type IPIPTrunkView struct {
	PeerURI string `json:"peer_uri,omitempty"`
}

// LegStreamView is a leg stream view.
type LegStreamView struct {
	// Stream identifier, stable for the life of the dialog. The primary stream is always "0".
	ID string `json:"id"`
	// The stream's SDP a=mid token (RFC 5888), used to correlate it across offer/answer.
	Mid string `json:"mid,omitempty"`
	// Position of the stream's m= line in the SDP. Fixed for the life of the dialog (RFC 3264 §8).
	Index int `json:"index"`
	// True for the call's main bidirectional audio stream, which cannot be removed or attached to a room independently.
	Primary bool `json:"primary"`
	// Negotiation state.
	State string `json:"state"`
	// Negotiated media direction from this server's point of view.
	Direction string `json:"direction"`
	// Direction requested by the application. Survives hold/unhold, unlike the negotiated direction.
	DesiredDirection string `json:"desired_direction,omitempty"`
	// Codec negotiated for this stream. Streams on one leg may use different codecs.
	Codec string `json:"codec,omitempty"`
	// Native sample rate of the stream's codec, in Hz.
	SampleRate int `json:"sample_rate,omitempty"`
	// Local RTP port. Each stream binds its own port; a shared transport is undefined without BUNDLE (RFC 9143).
	LocalPort int `json:"local_port,omitempty"`
	// Remote RTP address media is currently sent to.
	RemoteAddr string `json:"remote_addr,omitempty"`
	// The stream's a=label value (RFC 4574), for correlating it with external metadata.
	Label string `json:"label,omitempty"`
	// The stream's a=content value (RFC 4796), e.g. "main" for original audio and "alt" for a translated feed.
	Content string `json:"content,omitempty"`
	// The stream's a=lang value (RFC 8866): a BCP 47 language tag such as "en" or "es-ES".
	Lang string `json:"lang,omitempty"`
	// Room this stream's audio is mixed into. A secondary stream may sit in a different room than its leg.
	RoomID string `json:"room_id,omitempty"`
	// Routing role of this stream within its room. Streams carry their own role, independent of their leg's.
	Role string `json:"role,omitempty"`
}

// LiveKitParams is a live kit params.
type LiveKitParams struct {
	// LiveKit server endpoint (wss://...). Overrides LIVEKIT_URL.
	URL string `json:"url,omitempty"`
	// Pre-signed LiveKit JWT. Mutually exclusive with `room`/`identity` (mint mode); if both are present the token wins.
	Token string `json:"token,omitempty"`
	// LiveKit room name. Required when minting (i.e. `token` is empty AND LIVEKIT_TOKEN_SIGNING_ENABLED=true).
	Room string `json:"room,omitempty"`
	// LiveKit participant identity. Required when minting.
	Identity string `json:"identity,omitempty"`
	// Display name for the participant; surfaces in LK Room UIs.
	ParticipantName string `json:"participant_name,omitempty"`
	// LiveKit grant flags. Nil pointers default to publish=true, subscribe=true, data=false, admin=false.
	Permissions *LiveKitPermissions `json:"permissions,omitempty"`
	// Go duration string (e.g. "30m", "6h"). Used only when minting. Defaults to LIVEKIT_DEFAULT_TOKEN_TTL (6h).
	TokenTtl string `json:"token_ttl,omitempty"`
	// Override LIVEKIT_OPUS_BITRATE for this leg. 6000..510000.
	OpusBitrate int `json:"opus_bitrate,omitempty"`
}

// LiveKitPermissions is a live kit permissions.
type LiveKitPermissions struct {
	// Allow publishing tracks. Default true.
	CanPublish bool `json:"can_publish,omitempty"`
	// Allow subscribing to remote tracks. Default true.
	CanSubscribe bool `json:"can_subscribe,omitempty"`
	// Allow publishing data channel messages. Default false (audio bridge does not use data).
	CanPublishData bool `json:"can_publish_data,omitempty"`
	// Grant admin actions on the room (e.g., server-side MuteTrack of remote participants). Default false.
	RoomAdmin bool `json:"room_admin,omitempty"`
}

// OfferedCodec is a offered codec.
type OfferedCodec struct {
	Name        string `json:"name"`
	PayloadType int    `json:"payload_type"`
	ClockRate   int    `json:"clock_rate"`
	Priority    int    `json:"priority"`
}

// ParticipantInfo is a participant info.
type ParticipantInfo struct {
	ID   string `json:"id"`
	Aor  string `json:"aor,omitempty"`
	Name string `json:"name,omitempty"`
}

// RegistrationView is a registration view.
type RegistrationView struct {
	Aor                   string `json:"aor"`
	Contact               string `json:"contact"`
	Socket                string `json:"socket"`
	Transport             string `json:"transport"`
	UserAgent             string `json:"user_agent,omitempty"`
	CallID                string `json:"call_id,omitempty"`
	AppID                 string `json:"app_id,omitempty"`
	CreatedAt             string `json:"created_at"`
	LastRefresh           string `json:"last_refresh"`
	ExpiresAt             string `json:"expires_at"`
	GrantedExpiresSeconds int    `json:"granted_expires_seconds"`
}

// RegistrationsResponse is a registrations response.
type RegistrationsResponse struct {
	Bindings []RegistrationView `json:"bindings"`
}

// RoomRoutingView is a room routing view.
type RoomRoutingView struct {
	// Listener-role → list of allowed source roles. Roles absent from the matrix default to full mesh.
	Matrix map[string][]string `json:"matrix"`
}

// RoutingRowUpdate is a routing row update.
type RoutingRowUpdate struct {
	// The role whose row is being replaced.
	ListenerRole string `json:"listener_role"`
	// New list of allowed source roles for this listener role. Pass null to clear the row (full mesh).
	Sources []string `json:"sources"`
}

// SIPAuth is a SIP auth.
type SIPAuth struct {
	// Digest auth username. Optional for whatsapp legs (defaults to `from` with '+' stripped, per Meta's spec).
	Username string `json:"username,omitempty"`
	// Digest auth password.
	Password string `json:"password"`
}

// SIPRECParticipantView is a SIPREC participant view.
type SIPRECParticipantView struct {
	// The participant_id attribute from the recording metadata document.
	ParticipantID string `json:"participant_id"`
	// The participant's address of record, e.g. "sip:alice@example.com".
	Aor string `json:"aor,omitempty"`
	// The participant's display name, when the metadata carries one.
	Name string `json:"name,omitempty"`
}

// SIPRECSessionView is a SIPREC session view.
type SIPRECSessionView struct {
	// Leg carrying the recording session.
	LegID string `json:"leg_id"`
	// Communication session being recorded, from the metadata's sessionrecordingassoc.
	SessionID string `json:"session_id,omitempty"`
	// Data mode of the most recently applied metadata document (RFC 7865 §6.1).
	DataMode string `json:"data_mode,omitempty"`
	// Room this session's streams were attached to, when SIPREC_ROOM_MODE placed them in one.
	RoomID string `json:"room_id,omitempty"`
	// Every party currently recorded by this session.
	Participants []SIPRECParticipantView `json:"participants"`
	// Every negotiated media stream, joined to the participant it carries.
	Streams []SIPRECStreamView `json:"streams"`
	// The raw rs-metadata XML document as most recently received.
	Metadata string `json:"metadata,omitempty"`
	// What could be disproved about the metadata by the SDP it arrived with. Non-empty means the participant attributed to a stream may be wrong; the session is still recorded. Empty means nothing was disproved, which is not an assertion that the mapping is correct — an offer with no labels or no a=ssrc cname gives nothing to check against.
	Warnings []string `json:"warnings,omitempty"`
}

// SIPRECStream is a SIPREC stream.
type SIPRECStream struct {
	Label           string `json:"label,omitempty"`
	LegStreamID     string `json:"leg_stream_id,omitempty"`
	ParticipantID   string `json:"participant_id,omitempty"`
	ParticipantAor  string `json:"participant_aor,omitempty"`
	ParticipantName string `json:"participant_name,omitempty"`
}

// SIPRECStreamView is a SIPREC stream view.
type SIPRECStreamView struct {
	// Identifier of the leg stream carrying this recorded media, as used by /v1/legs/{id}/streams.
	LegStreamID string `json:"leg_stream_id"`
	// The stream's SDP a=mid token (RFC 5888).
	Mid string `json:"mid,omitempty"`
	// The stream's a=label value (RFC 4574). This is the key that binds the m= section to the recording metadata.
	Label string `json:"label,omitempty"`
	// Negotiated media direction. Always recvonly or inactive: a recording server never transmits.
	Direction string `json:"direction,omitempty"`
	// Codec negotiated for this stream.
	Codec string `json:"codec,omitempty"`
	// Room this stream's audio is mixed into, when it has been attached to one.
	RoomID string `json:"room_id,omitempty"`
	// Routing role of this stream within its room. Defaults to the participant's identity.
	Role string `json:"role,omitempty"`
	// Participant whose audio arrives on this stream, from the metadata's participantstreamassoc send binding.
	ParticipantID string `json:"participant_id,omitempty"`
	// Address of record of the participant sending on this stream.
	ParticipantAor string `json:"participant_aor,omitempty"`
	// Display name of the participant sending on this stream.
	ParticipantName string `json:"participant_name,omitempty"`
}

// SIPRegisterTrunkSpec is a SIP register trunk spec.
type SIPRegisterTrunkSpec struct {
	// Upstream registrar SIP URI (e.g. "sip:pbx.example.com:5060" or "sips:pbx.example.com:5061"). Transport is taken from the URI: a "sips:" scheme or a ";transport=tls" parameter selects TLS, ";transport=tcp" selects TCP, otherwise UDP. Note that "transport" is a URI parameter (";"), not a URI header ("?") — RFC 3261 section 19.1.
	RegistrarURI string `json:"registrar_uri"`
	// Next-hop SIP proxy for this trunk's REGISTER and for outbound INVITEs placed from its AOR, attached as a loose `Route` header (the Request-URI is left unchanged, and digest auth still targets `registrar_uri`). E.g. "sip:edge.example.com:5060;transport=tcp". Defaults to `SIP_OUTBOUND_PROXY`; when neither is set, requests go straight to `registrar_uri`.
	OutboundProxy string `json:"outbound_proxy,omitempty"`
	// Address-of-record this trunk REGISTERs (e.g. "sip:alice@pbx.example.com"). Becomes the From URI on outbound REGISTER, and the From / P-Asserted-Identity host on outbound INVITEs placed `from` this AOR.
	Aor string `json:"aor"`
	// Digest auth username. Defaults to the AOR user-part when empty.
	Username string `json:"username,omitempty"`
	// Digest auth password. Required. Never returned in any response.
	Password string `json:"password"`
	// Override the user-part of the Contact header sent in REGISTER. Defaults to the AOR user-part.
	ContactUser string `json:"contact_user,omitempty"`
	// Requested registration lifetime in seconds. Clamped to [SIP_OUTBOUND_REGISTRATION_MIN_EXPIRES_SECONDS, SIP_OUTBOUND_REGISTRATION_MAX_EXPIRES_SECONDS]. Default: SIP_OUTBOUND_REGISTRATION_DEFAULT_EXPIRES_SECONDS (3600).
	ExpiresSeconds int `json:"expires_seconds,omitempty"`
	// Accept this trunk's next-hop certificate without verifying it, for a `sips:` / `;transport=tls` registrar or outbound proxy whose certificate is self-signed, privately signed, or carries no SAN (`x509: certificate relies on legacy Common Name field`). Scoped to that peer's hostname — every other TLS peer is still verified in full, unlike the server-wide `SIP_TLS_INSECURE_SKIP_VERIFY`. Ignored (with a logged warning) when the next hop is not TLS, or when it is named by IP literal: such a dial sends no SNI and cannot be told apart from any other, so use `SIP_TLS_CA_FILE` or `SIP_TLS_INSECURE_SKIP_VERIFY` there. Prefer `SIP_TLS_CA_FILE` when the peer's CA can simply be trusted.
	TlsInsecureSkipVerify bool `json:"tls_insecure_skip_verify,omitempty"`
}

// SIPRegisterTrunkView is a SIP register trunk view.
type SIPRegisterTrunkView struct {
	RegistrarURI            string `json:"registrar_uri"`
	OutboundProxy           string `json:"outbound_proxy,omitempty"`
	Aor                     string `json:"aor"`
	Username                string `json:"username,omitempty"`
	ContactURI              string `json:"contact_uri,omitempty"`
	RequestedExpiresSeconds int    `json:"requested_expires_seconds"`
	GrantedExpiresSeconds   int    `json:"granted_expires_seconds,omitempty"`
	LastRegisteredAt        string `json:"last_registered_at,omitempty"`
	NextRefreshAt           string `json:"next_refresh_at,omitempty"`
	CallID                  string `json:"call_id,omitempty"`
	Cseq                    int    `json:"cseq,omitempty"`
	SourceAddress           string `json:"source_address,omitempty"`
	TlsInsecureSkipVerify   bool   `json:"tls_insecure_skip_verify,omitempty"`
}

// STTWord is a STT word.
type STTWord struct {
	Word       string  `json:"word"`
	Confidence float64 `json:"confidence"`
	StartMs    int     `json:"start_ms"`
	EndMs      int     `json:"end_ms"`
}

// TrunkView is a trunk view.
type TrunkView struct {
	ID          string                `json:"id"`
	Type        string                `json:"type"`
	AppID       string                `json:"app_id,omitempty"`
	Status      string                `json:"status"`
	LastError   string                `json:"last_error,omitempty"`
	CreatedAt   string                `json:"created_at"`
	SIPRegister *SIPRegisterTrunkView `json:"sip_register,omitempty"`
	IpIp        *IPIPTrunkView        `json:"ip_ip,omitempty"`
}

// TrunksListResponse is a trunks list response.
type TrunksListResponse struct {
	Trunks []TrunkView `json:"trunks"`
}

// WebRTCCandidatesResult is a web RTC candidates result.
type WebRTCCandidatesResult struct {
	Candidates []ICECandidateInit `json:"candidates"`
	Done       bool               `json:"done"`
}

// WebRTCOfferResult is a web RTC offer result.
type WebRTCOfferResult struct {
	LegID string `json:"leg_id"`
	SDP   string `json:"sdp"`
}

// ICECandidateInit is a WebRTC ICE candidate initialisation struct.
type ICECandidateInit struct {
	Candidate        string  `json:"candidate"`
	SDPMid           *string `json:"sdpMid,omitempty"`
	SDPMLineIndex    *uint16 `json:"sdpMLineIndex,omitempty"`
	UsernameFragment *string `json:"usernameFragment,omitempty"`
}
