// Code generated by cmd/generate from openapi.yaml. DO NOT EDIT.

package voiceblender

// StatusResponse is a status response.
type StatusResponse struct {
	// Instance identifier.
	InstanceID string `json:"instance_id,omitempty"`
	Status     string `json:"status"`
}
