// Code generated by cmd/generate from openapi.yaml. DO NOT EDIT.

package voiceblender

import (
	"context"
	"net/http"
)

// ListRooms list all rooms with participants
func (c *Client) ListRooms(ctx context.Context) ([]Room, error) {
	var out []Room
	if err := c.do(ctx, http.MethodGet, "/rooms", nil, &out); err != nil {
		return nil, err
	}
	for i := range out {
		out[i].client = c
	}
	return out, nil
}

// CreateRoom create a room
func (c *Client) CreateRoom(ctx context.Context, req CreateRoomRequest) (*Room, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out Room
	if err := c.do(ctx, http.MethodPost, "/rooms", body, &out); err != nil {
		return nil, err
	}
	out.client = c
	return &out, nil
}

// GetRoom get a room with participants
func (c *Client) GetRoom(ctx context.Context, id string) (*Room, error) {
	var out Room
	if err := c.do(ctx, http.MethodGet, "/rooms/"+id, nil, &out); err != nil {
		return nil, err
	}
	out.client = c
	return &out, nil
}

// Delete delete a room
func (r *Room) Delete(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, r.client.do(ctx, http.MethodDelete, "/rooms/"+r.ID, nil, &out)
}

// AddLeg add or move a leg to a room
func (r *Room) AddLeg(ctx context.Context, req AddLegRequest) (*AddLegResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out AddLegResponse
	return &out, r.client.do(ctx, http.MethodPost, "/rooms/"+r.ID+"/legs", body, &out)
}

// RemoveLeg remove a leg from a room
func (r *Room) RemoveLeg(ctx context.Context, legID string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, r.client.do(ctx, http.MethodDelete, "/rooms/"+r.ID+"/legs/"+legID, nil, &out)
}

// Play play audio to a room
func (r *Room) Play(ctx context.Context, req PlaybackRequest) (*PlaybackResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out PlaybackResponse
	return &out, r.client.do(ctx, http.MethodPost, "/rooms/"+r.ID+"/play", body, &out)
}

// VolumePlay change the volume of an active room playback
func (r *Room) VolumePlay(ctx context.Context, playbackID string, req VolumeRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, r.client.do(ctx, http.MethodPatch, "/rooms/"+r.ID+"/play/"+playbackID, body, &out)
}

// StopPlay stop room playback
func (r *Room) StopPlay(ctx context.Context, playbackID string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, r.client.do(ctx, http.MethodDelete, "/rooms/"+r.ID+"/play/"+playbackID, nil, &out)
}

// PlayTTS synthesize speech and play it into a room
func (r *Room) PlayTTS(ctx context.Context, req TTSRequest) (*TTSResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out TTSResponse
	return &out, r.client.do(ctx, http.MethodPost, "/rooms/"+r.ID+"/tts", body, &out)
}

// Record start recording the room mix to a WAV file
func (r *Room) Record(ctx context.Context, req RecordingRequest) (*RecordingResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out RecordingResponse
	return &out, r.client.do(ctx, http.MethodPost, "/rooms/"+r.ID+"/record", body, &out)
}

// StopRecord stop room recording
func (r *Room) StopRecord(ctx context.Context) (*RecordingResponse, error) {
	var out RecordingResponse
	return &out, r.client.do(ctx, http.MethodDelete, "/rooms/"+r.ID+"/record", nil, &out)
}

// PauseRecord pause a room recording
func (r *Room) PauseRecord(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, r.client.do(ctx, http.MethodPost, "/rooms/"+r.ID+"/record/pause", nil, &out)
}

// ResumeRecord resume a paused room recording
func (r *Room) ResumeRecord(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, r.client.do(ctx, http.MethodPost, "/rooms/"+r.ID+"/record/resume", nil, &out)
}

// STT start speech-to-text on all room participants
func (r *Room) STT(ctx context.Context, req STTRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, r.client.do(ctx, http.MethodPost, "/rooms/"+r.ID+"/stt", body, &out)
}

// StopSTT stop speech-to-text on a room
func (r *Room) StopSTT(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, r.client.do(ctx, http.MethodDelete, "/rooms/"+r.ID+"/stt", nil, &out)
}

// ElevenLabsAgent attach an ElevenLabs ConvAI agent to a room
func (r *Room) ElevenLabsAgent(ctx context.Context, req ElevenLabsAgentRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, r.client.do(ctx, http.MethodPost, "/rooms/"+r.ID+"/agent/elevenlabs", body, &out)
}

// VAPIAgent attach a VAPI agent to a room
func (r *Room) VAPIAgent(ctx context.Context, req VAPIAgentRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, r.client.do(ctx, http.MethodPost, "/rooms/"+r.ID+"/agent/vapi", body, &out)
}

// PipecatAgent attach a Pipecat bot to a room
func (r *Room) PipecatAgent(ctx context.Context, req PipecatAgentRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, r.client.do(ctx, http.MethodPost, "/rooms/"+r.ID+"/agent/pipecat", body, &out)
}

// DeepgramAgent attach a Deepgram Voice Agent to a room
func (r *Room) DeepgramAgent(ctx context.Context, req DeepgramAgentRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, r.client.do(ctx, http.MethodPost, "/rooms/"+r.ID+"/agent/deepgram", body, &out)
}

// AgentMessage inject a message into a running agent session on a room
func (r *Room) AgentMessage(ctx context.Context, req AgentMessageRequest) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, r.client.do(ctx, http.MethodPost, "/rooms/"+r.ID+"/agent/message", body, &out)
}

// StopAgent detach the agent from a room
func (r *Room) StopAgent(ctx context.Context) (*StatusResponse, error) {
	var out StatusResponse
	return &out, r.client.do(ctx, http.MethodDelete, "/rooms/"+r.ID+"/agent", nil, &out)
}
