// Code generated by cmd/generate from openapi.yaml. DO NOT EDIT.

package voiceblender

import (
	"context"
	"net/http"
)

// ListSIPTrunks list configured SIP trunks
func (c *Client) ListSIPTrunks(ctx context.Context) (*TrunksListResponse, error) {
	var out TrunksListResponse
	return &out, c.do(ctx, http.MethodGet, "/sip/trunks", nil, &out)
}

// CreateSIPTrunk create an outbound SIP trunk (REGISTER or static peering)
func (c *Client) CreateSIPTrunk(ctx context.Context, req CreateTrunkRequest) (*CreateTrunkResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out CreateTrunkResponse
	return &out, c.do(ctx, http.MethodPost, "/sip/trunks", body, &out)
}

// GetSIPTrunk get a single SIP trunk
func (c *Client) GetSIPTrunk(ctx context.Context, id string) (*TrunkView, error) {
	var out TrunkView
	return &out, c.do(ctx, http.MethodGet, "/sip/trunks/"+id, nil, &out)
}

// DeleteSIPTrunk unregister and remove a SIP trunk
func (c *Client) DeleteSIPTrunk(ctx context.Context, id string) (*StatusResponse, error) {
	var out StatusResponse
	return &out, c.do(ctx, http.MethodDelete, "/sip/trunks/"+id, nil, &out)
}
