// Code generated by cmd/generate from asyncapi.yaml. DO NOT EDIT.

package voiceblender

import (
	"context"
	"encoding/json"
)

// ── VSI payload / result schemas ──────────────────────────────────────────

// AddLegPayload is a add leg payload.
type AddLegPayload struct {
	RoomID     string `json:"room_id"`
	LegID      string `json:"leg_id"`
	Mute       bool   `json:"mute,omitempty"`
	Deaf       bool   `json:"deaf,omitempty"`
	AcceptDTMF bool   `json:"accept_dtmf,omitempty"`
}

// AddLegToRoomResult is a add leg to room result.
type AddLegToRoomResult struct {
	Status string `json:"status"`
	RoomID string `json:"room_id"`
	LegID  string `json:"leg_id"`
}

// DTMFPayload is a d t m f payload.
type DTMFPayload struct {
	ID     string `json:"id"`
	Digits string `json:"digits"`
}

// IDPayload is a i d payload.
type IDPayload struct {
	ID string `json:"id"`
}

// RTTPayload is a r t t payload.
type RTTPayload struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

// RoomLegPayload is a room leg payload.
type RoomLegPayload struct {
	RoomID string `json:"room_id"`
	LegID  string `json:"leg_id"`
}

// VSIAnswerLegPayload is a v s i answer leg payload.
type VSIAnswerLegPayload struct {
	ID              string `json:"id"`
	SpeechDetection bool   `json:"speech_detection,omitempty"`
	Codec           string `json:"codec,omitempty"`
}

// VSIDeleteLegPayload is a v s i delete leg payload.
type VSIDeleteLegPayload struct {
	ID     string `json:"id"`
	Reason string `json:"reason,omitempty"`
}

// VSIStatusResponse is a v s i status response.
type VSIStatusResponse struct {
	Status string `json:"status"`
}

// VSIWebRTCAddCandidatePayload is a v s i web r t c add candidate payload.
type VSIWebRTCAddCandidatePayload struct {
	ID        string           `json:"id"`
	Candidate ICECandidateInit `json:"candidate"`
}

// WebRTCCandidatesResult is a web r t c candidates result.
type WebRTCCandidatesResult struct {
	Candidates []ICECandidateInit `json:"candidates"`
	Done       bool               `json:"done"`
}

// WebRTCOfferResult is a web r t c offer result.
type WebRTCOfferResult struct {
	LegID string `json:"leg_id"`
	SDP   string `json:"sdp"`
}

// ── VSI command methods on *EventStream ───────────────────────────────────

// ListLegs list all active legs
func (s *EventStream) ListLegs(ctx context.Context) ([]json.RawMessage, error) {
	var out []json.RawMessage
	return out, s.call(ctx, "list_legs", nil, &out)
}

// GetLeg get a single leg by id
func (s *EventStream) GetLeg(ctx context.Context, payload IDPayload) (json.RawMessage, error) {
	var out json.RawMessage
	return out, s.call(ctx, "get_leg", payload, &out)
}

// CreateLeg originate an outbound leg
func (s *EventStream) CreateLeg(ctx context.Context, payload CreateLegRequest) (json.RawMessage, error) {
	var out json.RawMessage
	return out, s.call(ctx, "create_leg", payload, &out)
}

// AnswerLeg answer a ringing inbound leg
func (s *EventStream) AnswerLeg(ctx context.Context, payload VSIAnswerLegPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "answer_leg", payload, &out)
}

// DeleteLeg hang up a leg
func (s *EventStream) DeleteLeg(ctx context.Context, payload VSIDeleteLegPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "delete_leg", payload, &out)
}

// MuteLeg mute a leg
func (s *EventStream) MuteLeg(ctx context.Context, payload IDPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "mute_leg", payload, &out)
}

// UnmuteLeg unmute a leg
func (s *EventStream) UnmuteLeg(ctx context.Context, payload IDPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "unmute_leg", payload, &out)
}

// DeafLeg deafen a leg (stop receiving room audio)
func (s *EventStream) DeafLeg(ctx context.Context, payload IDPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "deaf_leg", payload, &out)
}

// UndeafLeg undeafen a leg
func (s *EventStream) UndeafLeg(ctx context.Context, payload IDPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "undeaf_leg", payload, &out)
}

// HoldLeg put a SIP leg on hold
func (s *EventStream) HoldLeg(ctx context.Context, payload IDPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "hold_leg", payload, &out)
}

// UnholdLeg resume a held SIP leg
func (s *EventStream) UnholdLeg(ctx context.Context, payload IDPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "unhold_leg", payload, &out)
}

// SendLegDTMF send DTMF digits on a leg
func (s *EventStream) SendLegDTMF(ctx context.Context, payload DTMFPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "send_leg_dtmf", payload, &out)
}

// AcceptLegDTMF enable DTMF reception
func (s *EventStream) AcceptLegDTMF(ctx context.Context, payload IDPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "accept_leg_dtmf", payload, &out)
}

// RejectLegDTMF disable DTMF reception
func (s *EventStream) RejectLegDTMF(ctx context.Context, payload IDPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "reject_leg_dtmf", payload, &out)
}

// SendLegRTT send Real-Time Text (T.140) on a SIP leg
func (s *EventStream) SendLegRTT(ctx context.Context, payload RTTPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "send_leg_rtt", payload, &out)
}

// AcceptLegRTT enable RTT reception
func (s *EventStream) AcceptLegRTT(ctx context.Context, payload IDPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "accept_leg_rtt", payload, &out)
}

// RejectLegRTT disable RTT reception
func (s *EventStream) RejectLegRTT(ctx context.Context, payload IDPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "reject_leg_rtt", payload, &out)
}

// WebRTCOffer establish a WebRTC leg via SDP offer/answer
func (s *EventStream) WebRTCOffer(ctx context.Context, payload WebRTCOfferRequest) (WebRTCOfferResult, error) {
	var out WebRTCOfferResult
	return out, s.call(ctx, "webrtc_offer", payload, &out)
}

// WebRTCAddCandidate add a remote ICE candidate to a WebRTC leg
func (s *EventStream) WebRTCAddCandidate(ctx context.Context, payload VSIWebRTCAddCandidatePayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "webrtc_add_candidate", payload, &out)
}

// WebRTCGetCandidates drain server-gathered ICE candidates for a WebRTC leg
func (s *EventStream) WebRTCGetCandidates(ctx context.Context, payload IDPayload) (WebRTCCandidatesResult, error) {
	var out WebRTCCandidatesResult
	return out, s.call(ctx, "webrtc_get_candidates", payload, &out)
}

// ListRooms list all rooms
func (s *EventStream) ListRooms(ctx context.Context) ([]json.RawMessage, error) {
	var out []json.RawMessage
	return out, s.call(ctx, "list_rooms", nil, &out)
}

// GetRoom get a single room by id
func (s *EventStream) GetRoom(ctx context.Context, payload IDPayload) (json.RawMessage, error) {
	var out json.RawMessage
	return out, s.call(ctx, "get_room", payload, &out)
}

// CreateRoom create a room
func (s *EventStream) CreateRoom(ctx context.Context, payload CreateRoomRequest) (json.RawMessage, error) {
	var out json.RawMessage
	return out, s.call(ctx, "create_room", payload, &out)
}

// DeleteRoom delete a room
func (s *EventStream) DeleteRoom(ctx context.Context, payload IDPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "delete_room", payload, &out)
}

// AddLegToRoom add or move a leg into a room
func (s *EventStream) AddLegToRoom(ctx context.Context, payload AddLegPayload) (AddLegToRoomResult, error) {
	var out AddLegToRoomResult
	return out, s.call(ctx, "add_leg_to_room", payload, &out)
}

// RemoveLegFromRoom remove a leg from a room
func (s *EventStream) RemoveLegFromRoom(ctx context.Context, payload RoomLegPayload) (VSIStatusResponse, error) {
	var out VSIStatusResponse
	return out, s.call(ctx, "remove_leg_from_room", payload, &out)
}
