// Code generated by cmd/generate from openapi.yaml. DO NOT EDIT.

package voiceblender

import (
	"context"
	"net/http"
)

// GetICECandidates get server-side ICE candidates for a WebRTC leg (trickle ICE)
func (l *Leg) GetICECandidates(ctx context.Context) (*ICECandidatesResponse, error) {
	var out ICECandidatesResponse
	return &out, l.client.do(ctx, http.MethodGet, "/legs/"+l.ID+"/ice-candidates", nil, &out)
}

// AddICECandidate send a remote ICE candidate to a WebRTC leg (trickle ICE)
func (l *Leg) AddICECandidate(ctx context.Context, req ICECandidateInit) (*StatusResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out StatusResponse
	return &out, l.client.do(ctx, http.MethodPost, "/legs/"+l.ID+"/ice-candidates", body, &out)
}

// WebRTCOffer establish a WebRTC leg via SDP offer/answer
func (c *Client) WebRTCOffer(ctx context.Context, req WebRTCOfferRequest) (*WebRTCOfferResponse, error) {
	body, err := encodeJSON(req)
	if err != nil {
		return nil, err
	}
	var out WebRTCOfferResponse
	return &out, c.do(ctx, http.MethodPost, "/webrtc/offer", body, &out)
}
