// Command rtt is a Real-Time Text (T.140 / RFC 4103) demo for VoiceBlender.
//
// Behaviour:
//   - Connects to VoiceBlender via the VSI WebSocket — no webhook config needed.
//   - Answers any inbound SIP call. RTT is negotiated automatically when the
//     remote offer includes an m=text section (the VoiceBlender server must
//     run with RTT_ENABLED=true).
//   - Hosts a tiny web UI at LISTEN_ADDR. Browser ↔ server runs over a
//     WebSocket so the letter-by-letter rtt.received chunks update the
//     incoming text view live as the remote types. Outgoing messages travel
//     on the same socket and are pushed to the leg via SendRTT.
//   - Single-call demo: while a call is active any other inbound call is
//     rejected with "busy". Reload picks up an in-progress session.
//
// Run:
//
//	go run ./examples/rtt
//
// Then place an RTT-capable SIP call to the VoiceBlender server and open
// http://localhost:8090 in a browser.
//
// Environment:
//
//	VOICEBLENDER_URL  default http://localhost:8080/v1
//	LISTEN_ADDR       default :8090
package main

import (
	"context"
	"embed"
	"encoding/json"
	"errors"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"sync"
	"time"

	voiceblender "github.com/VoiceBlender/voice-go"
	"github.com/coder/websocket"
)

//go:embed index.html
var assets embed.FS

// uiEvent is what the server pushes to the browser over the WebSocket.
type uiEvent struct {
	Kind string `json:"kind"`           // "call_started", "call_ended", "rtt", "error"
	From string `json:"from,omitempty"` // caller URI on call_started
	Dir  string `json:"dir,omitempty"`  // "in" or "out" for kind=="rtt"
	Text string `json:"text,omitempty"` // also error message for kind=="error"
	Loss bool   `json:"loss,omitempty"` // RFC 2198 loss marker on incoming RTT
	Time int64  `json:"time"`           // unix ms
}

// clientMsg is what the browser sends to the server over the WebSocket.
type clientMsg struct {
	Type string `json:"type"` // "send"
	Text string `json:"text,omitempty"`
}

// app holds the single active session and the set of WebSocket subscribers.
type app struct {
	client *voiceblender.Client
	log    *slog.Logger

	mu      sync.Mutex
	curLeg  string
	curFrom string
	clients map[chan uiEvent]struct{}
}

func main() {
	log := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelInfo}))

	baseURL := envOr("VOICEBLENDER_URL", "http://localhost:8080/v1")
	listenAddr := envOr("LISTEN_ADDR", ":8090")

	a := &app{
		client:  voiceblender.New(voiceblender.WithBaseURL(baseURL)),
		log:     log,
		clients: make(map[chan uiEvent]struct{}),
	}

	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt)
	defer cancel()

	// One websocket pumps every event into the client's hub. Subscribe API
	// on Client / *Leg reads from the hub.
	go func() {
		if err := a.client.RunEventStream(ctx); err != nil && ctx.Err() == nil {
			log.Error("event stream", "error", err)
			cancel()
		}
	}()

	go a.handleRingings(ctx)

	mux := http.NewServeMux()
	mux.Handle("/", http.FileServer(http.FS(assets)))
	mux.HandleFunc("/ws", a.wsHandler)

	srv := &http.Server{Addr: listenAddr, Handler: mux}
	log.Info("rtt demo ready", "base_url", baseURL, "listen", listenAddr)
	go func() {
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Error("http", "error", err)
			cancel()
		}
	}()

	<-ctx.Done()
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer shutdownCancel()
	_ = srv.Shutdown(shutdownCtx)
}

// handleRingings answers inbound SIP calls and starts a per-call RTT pump.
func (a *app) handleRingings(ctx context.Context) {
	sub := a.client.Subscribe(voiceblender.EventLegRinging)
	defer sub.Close()

	for {
		ev, err := sub.Next(ctx)
		if err != nil {
			return
		}
		ring := ev.(*voiceblender.LegRingingEvent)
		if ring.LegType != string(voiceblender.LegTypeSIPInbound) {
			continue
		}

		a.mu.Lock()
		busy := a.curLeg != ""
		if !busy {
			a.curLeg = ring.LegID
			a.curFrom = ring.From
		}
		a.mu.Unlock()

		if busy {
			a.log.Info("busy — rejecting", "leg_id", ring.LegID, "from", ring.From)
			_, _ = a.client.Leg(ring.LegID).Hangup(ctx, voiceblender.DeleteLegRequest{Reason: "busy"})
			continue
		}

		a.log.Info("inbound", "leg_id", ring.LegID, "from", ring.From)
		go a.runCall(ctx, ring)
	}
}

// runCall answers the leg, fans rtt.received events out to web clients, and
// cleans up when the call ends. RTT negotiation is purely SDP-driven: if the
// remote offer included m=text and the server has RTT_ENABLED, the answer
// generated by Answer() will include it too.
func (a *app) runCall(ctx context.Context, ring *voiceblender.LegRingingEvent) {
	leg := a.client.Leg(ring.LegID)

	// Subscribe before answering so we don't miss early rtt.received events.
	sub := leg.Subscribe(
		voiceblender.EventRttReceived,
		voiceblender.EventLegDisconnected,
	)
	defer sub.Close()

	if _, err := leg.Answer(ctx, voiceblender.AnswerLegRequest{}); err != nil {
		a.log.Error("answer", "leg_id", ring.LegID, "error", err)
		a.endCall(ring.LegID)
		return
	}

	a.broadcast(uiEvent{Kind: "call_started", From: ring.From, Time: nowMs()})
	defer func() {
		a.broadcast(uiEvent{Kind: "call_ended", Time: nowMs()})
		a.endCall(ring.LegID)
	}()

	for {
		ev, err := sub.Next(ctx)
		if err != nil {
			return
		}
		switch e := ev.(type) {
		case *voiceblender.RttReceivedEvent:
			a.log.Info("rtt in", "leg_id", e.LegID, "seq", e.Seq, "loss", e.LossMarker, "text", e.Text)
			a.broadcast(uiEvent{Kind: "rtt", Dir: "in", Text: e.Text, Loss: e.LossMarker, Time: nowMs()})
		case *voiceblender.LegDisconnectedEvent:
			a.log.Info("leg disconnected", "leg_id", e.LegID)
			return
		}
	}
}

func (a *app) endCall(legID string) {
	a.mu.Lock()
	defer a.mu.Unlock()
	if a.curLeg == legID {
		a.curLeg = ""
		a.curFrom = ""
	}
}

// wsHandler serves one browser tab. Inbound RTT chunks are pushed in real
// time; outgoing {type:"send",text:"..."} frames are forwarded to SendRTT.
func (a *app) wsHandler(w http.ResponseWriter, r *http.Request) {
	conn, err := websocket.Accept(w, r, &websocket.AcceptOptions{
		// Localhost-only demo; loosen as needed for cross-origin embedding.
		InsecureSkipVerify: true,
	})
	if err != nil {
		a.log.Warn("ws accept", "error", err)
		return
	}
	defer conn.Close(websocket.StatusInternalError, "closing")

	ctx, cancel := context.WithCancel(r.Context())
	defer cancel()

	ch := make(chan uiEvent, 64)
	a.mu.Lock()
	a.clients[ch] = struct{}{}
	curLeg := a.curLeg
	curFrom := a.curFrom
	a.mu.Unlock()
	defer func() {
		a.mu.Lock()
		delete(a.clients, ch)
		a.mu.Unlock()
	}()

	// Re-emit call_started so a page reload during an active call resumes
	// in the right state. Past RTT chunks are not replayed.
	if curLeg != "" {
		_ = writeJSON(ctx, conn, uiEvent{Kind: "call_started", From: curFrom, Time: nowMs()})
	}

	// Reader goroutine: drains client → server frames (outgoing RTT and
	// peer-initiated close). Cancels ctx on exit so the writer loop quits.
	go func() {
		defer cancel()
		for {
			_, data, err := conn.Read(ctx)
			if err != nil {
				a.log.Info("ws read end", "error", err)
				return
			}
			var msg clientMsg
			if err := json.Unmarshal(data, &msg); err != nil {
				a.log.Warn("ws bad json", "raw", string(data), "error", err)
				continue
			}
			a.log.Info("ws recv", "type", msg.Type, "text", msg.Text)
			if msg.Type == "send" && msg.Text != "" {
				a.sendRTT(msg.Text)
			}
		}
	}()

	// Writer loop: server → client frames.
	for {
		select {
		case ev := <-ch:
			if err := writeJSON(ctx, conn, ev); err != nil {
				return
			}
		case <-ctx.Done():
			conn.Close(websocket.StatusNormalClosure, "")
			return
		}
	}
}

// sendRTT pushes outgoing text on the active leg and echoes it to all UI
// clients so the local sender sees their own messages. Uses a fresh context
// so a flaky/closing browser WS doesn't tear down the API call mid-flight.
func (a *app) sendRTT(text string) {
	a.mu.Lock()
	legID := a.curLeg
	a.mu.Unlock()
	if legID == "" {
		a.broadcast(uiEvent{Kind: "error", Text: "no active call", Time: nowMs()})
		return
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if _, err := a.client.Leg(legID).SendRTT(ctx, voiceblender.RTTRequest{Text: text}); err != nil {
		a.log.Error("send rtt", "leg_id", legID, "error", err)
		a.broadcast(uiEvent{Kind: "error", Text: "send failed: " + err.Error(), Time: nowMs()})
		return
	}
	a.log.Info("rtt out", "leg_id", legID, "text", text)
	a.broadcast(uiEvent{Kind: "rtt", Dir: "out", Text: text, Time: nowMs()})
}

func writeJSON(ctx context.Context, conn *websocket.Conn, v any) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	writeCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	return conn.Write(writeCtx, websocket.MessageText, b)
}

func (a *app) broadcast(ev uiEvent) {
	a.mu.Lock()
	defer a.mu.Unlock()
	for ch := range a.clients {
		select {
		case ch <- ev:
		default:
			// slow consumer — drop rather than block the call goroutine.
		}
	}
}

func nowMs() int64 { return time.Now().UnixMilli() }

func envOr(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}
